/** The screen registry — the shared surface for the phone-screen journey.
 *
 *  FAN-OUT CONTRACT — read before adding screens:
 *  - Each screen lives in exactly ONE file: `src/screens/<id>.tsx`, default-exporting
 *    a component that takes no required props and renders the screen BODY only
 *    (the phone chrome and status bar are supplied by PhoneScreen).
 *  - Register it in SCREENS below. Never edit another author's screen file.
 *  - A screen declares the API call behind it so the site can show them together —
 *    that pairing is the whole point of the demo.
 *  - Do not edit this file during fan-out beyond adding your own SCREENS entries.
 */
import type { ComponentType } from "react";
import Signup, { meta as SignupMeta } from "./signup";
import KycProcessing, { meta as KycProcessingMeta } from "./kyc-processing";
import KycApproved, { meta as KycApprovedMeta } from "./kyc-approved";
import AccountOpen, { meta as AccountOpenMeta } from "./account-open";
import TierLimits, { meta as TierLimitsMeta } from "./tier-limits";
import ReceivingDetails, { meta as ReceivingDetailsMeta } from "./receiving-details";
import DepositRails, { meta as DepositRailsMeta } from "./deposit-rails";
import DepositOnchain, { meta as DepositOnchainMeta } from "./deposit-onchain";
import DepositPending, { meta as DepositPendingMeta } from "./deposit-pending";
import FundedHome, { meta as FundedHomeMeta } from "./funded-home";
import CardIssued, { meta as CardIssuedMeta } from "./card-issued";
import CardControls, { meta as CardControlsMeta } from "./card-controls";
import CardTap, { meta as CardTapMeta } from "./card-tap";
import CardDeclined, { meta as CardDeclinedMeta } from "./card-declined";
import LinkExternal, { meta as LinkExternalMeta } from "./link-external";
import PayoutReceipt, { meta as PayoutReceiptMeta } from "./payout-receipt";

export type ScreenMeta = {
  id: string;
  /** Which journey this belongs to, for grouping in the UI. */
  journey: "onboarding" | "funding" | "spending" | "payout" | "product";
  /** Shown above the phone. */
  title: string;
  blurb: string;
  /** The call behind this screen — method + path from the real catalogue. */
  endpoint: string;
  /** Sample request/response shown beside the screen. */
  code: string;
  /** Is this screen driven by live API data, or an illustration? */
  live?: boolean;
};

export type ScreenModule = { meta: ScreenMeta; Component: ComponentType<any> };

/** Journeys in the order a developer would walk them. */
export const JOURNEYS: { id: ScreenMeta["journey"]; label: string; blurb: string }[] = [
  { id: "onboarding", label: "Onboarding", blurb: "Sign a customer up, run KYC, open the account." },
  { id: "funding", label: "Funding", blurb: "Get money in — bank rails or on-chain." },
  { id: "spending", label: "Spending", blurb: "Issue a card and spend the balance." },
  { id: "payout", label: "Payout", blurb: "Send money out and settle to a bank account." },
  { id: "product", label: "Products", blurb: "The rest of the surface at a glance." },
];

/** Every screen in the journey. Order matters — this is the sequence a visitor walks. */
export const SCREENS: ScreenModule[] = [
  { meta: SignupMeta, Component: Signup },
  { meta: KycProcessingMeta, Component: KycProcessing },
  { meta: KycApprovedMeta, Component: KycApproved },
  { meta: AccountOpenMeta, Component: AccountOpen },
  { meta: TierLimitsMeta, Component: TierLimits },
  { meta: ReceivingDetailsMeta, Component: ReceivingDetails },
  { meta: DepositRailsMeta, Component: DepositRails },
  { meta: DepositOnchainMeta, Component: DepositOnchain },
  { meta: DepositPendingMeta, Component: DepositPending },
  { meta: FundedHomeMeta, Component: FundedHome },
  { meta: CardIssuedMeta, Component: CardIssued },
  { meta: CardControlsMeta, Component: CardControls },
  { meta: CardTapMeta, Component: CardTap },
  { meta: CardDeclinedMeta, Component: CardDeclined },
  { meta: LinkExternalMeta, Component: LinkExternal },
  { meta: PayoutReceiptMeta, Component: PayoutReceipt },
];

export const byJourney = (j: ScreenMeta["journey"]) => SCREENS.filter((s) => s.meta.journey === j);
export const screenById = (id: string) => SCREENS.find((s) => s.meta.id === id);
