import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "fragment", name: "Fragment", url: "https://fragment.dev/", kind: "Ledger infrastructure", summary: "Developer infrastructure for double-entry ledgers and financial event accounting.", regions: ["Global"], categories: ["operations"], capabilities: ["Ledger", "Accounting", "Financial events"]},
  {id: "sequence", name: "Sequence", url: "https://www.sequencehq.com/", kind: "Financial operations", summary: "Financial operations, billing and ledger workflows for modern software businesses.", regions: ["Global"], categories: ["operations"], capabilities: ["Financial operations", "Ledger", "Billing"]},
  {id: "kani", name: "Kani Payments", url: "https://kanipayments.com/", kind: "Reconciliation", summary: "Payments reconciliation, scheme reporting and data operations for card programmes.", regions: ["UK", "Europe", "Global"], categories: ["operations", "cards"], capabilities: ["Reconciliation", "Scheme reporting", "Card data"]},
  {id: "duco", name: "Duco", url: "https://du.co/", kind: "Reconciliation", summary: "Data automation and reconciliation for financial institutions and complex operations.", regions: ["Global"], categories: ["operations"], capabilities: ["Reconciliation", "Data automation", "Controls"]},
  {id: "hummingbird", name: "Hummingbird", url: "https://www.hummingbird.co/", kind: "Compliance operations", summary: "Financial-crime investigations, case management and regulatory reporting workflows.", regions: ["Global"], categories: ["operations", "compliance"], capabilities: ["Case management", "Investigations", "Reporting"]},
  {id: "vgs", name: "VGS", url: "https://www.verygoodsecurity.com/", kind: "Data security", summary: "Tokenisation and secure handling of sensitive payment and identity data.", regions: ["Global"], categories: ["operations", "cards"], capabilities: ["Data vaulting", "Tokenisation", "PCI scope reduction"]},
  {id: "cable", name: "Cable", url: "https://cable.tech/", kind: "Compliance operations", summary: "Automated financial-crime assurance and control testing for fintech compliance programmes.", regions: ["US", "UK", "Global"], categories: ["operations", "compliance"], capabilities: ["Control assurance", "Compliance monitoring", "Testing"]},
];
