import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "bitgo", name: "BitGo", url: "https://www.bitgo.com/", kind: "Qualified custody", summary: "Institutional custody, wallets, settlement and staking infrastructure for digital assets.", regions: ["Global"], categories: ["custody", "stablecoins"], capabilities: ["Custody", "Wallets", "Settlement"]},
  {id: "anchorage", name: "Anchorage Digital", url: "https://www.anchorage.com/", kind: "Digital-asset bank", summary: "Institutional custody, settlement, governance and digital-asset banking services.", regions: ["US", "Global"], categories: ["custody", "stablecoins"], capabilities: ["Custody", "Settlement", "Institutional access"]},
  {id: "copper", name: "Copper", url: "https://copper.co/", kind: "Institutional custody", summary: "Custody, collateral and settlement infrastructure for institutional digital-asset markets.", regions: ["Global"], categories: ["custody", "fx"], capabilities: ["Custody", "Collateral", "Settlement"]},
  {id: "coinbase-prime", name: "Coinbase Prime", url: "https://www.coinbase.com/prime", kind: "Institutional platform", summary: "Institutional custody, trading, financing and execution for digital assets.", regions: ["Global"], categories: ["custody", "fx"], capabilities: ["Custody", "Execution", "Prime services"]},
  {id: "fordefi", name: "Fordefi", url: "https://www.fordefi.com/", kind: "Wallet infrastructure", summary: "Institutional MPC wallets and policy controls for onchain operations.", regions: ["Global"], categories: ["custody"], capabilities: ["MPC wallets", "Policies", "DeFi access"]},
  {id: "utila", name: "Utila", url: "https://utila.io/", kind: "Wallet infrastructure", summary: "Institutional wallet operations, policy controls and asset-management workflows.", regions: ["Global"], categories: ["custody"], capabilities: ["Wallet operations", "Policies", "Treasury"]},
  {id: "dfns", name: "Dfns", url: "https://www.dfns.co/", kind: "Wallet infrastructure", summary: "Wallet-as-a-service APIs for secure key management, signing and embedded wallets.", regions: ["Global"], categories: ["custody"], capabilities: ["Wallet APIs", "Signing", "Key management"]},
  {id: "privy", name: "Privy", url: "https://www.privy.io/", kind: "Embedded wallets", summary: "Embedded wallet and authentication infrastructure for consumer-facing applications.", regions: ["Global"], categories: ["custody"], capabilities: ["Embedded wallets", "Authentication", "Recovery"]},
  {id: "turnkey", name: "Turnkey", url: "https://www.turnkey.com/", kind: "Wallet infrastructure", summary: "Secure signing, policy and wallet infrastructure built around isolated key operations.", regions: ["Global"], categories: ["custody"], capabilities: ["Signing", "Policies", "Wallets"]},
  {id: "dynamic", name: "Dynamic", url: "https://www.dynamic.xyz/", kind: "Embedded wallets", summary: "Wallet and identity infrastructure for onboarding users into onchain products.", regions: ["Global"], categories: ["custody"], capabilities: ["Embedded wallets", "Authentication", "Onboarding"]},
  {id: "safe", name: "Safe", url: "https://safe.global/", kind: "Smart-account infrastructure", summary: "Smart accounts, multisignature controls and programmable account infrastructure.", regions: ["Global"], categories: ["custody"], capabilities: ["Smart accounts", "Multisig", "Policies"]},
  {id: "rain", name: "Rain", url: "https://www.rain.xyz/", kind: "Card infrastructure", summary: "Stablecoin-powered card issuing, wallets, settlement and programme infrastructure.", regions: ["Global"], categories: ["cards", "stablecoins", "custody"], capabilities: ["Card issuing", "Stablecoin settlement", "Wallets"], featured: true},
];
