import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "360t", name: "360T", url: "https://www.360t.com/", kind: "FX venue", summary: "Institutional FX trading, liquidity and workflow infrastructure.", regions: ["Global"], categories: ["fx"], capabilities: ["Institutional FX", "Liquidity", "Execution"]},
  {id: "fxspotstream", name: "FXSpotStream", url: "https://www.fxspotstream.com/", kind: "FX liquidity network", summary: "Institutional API access to bank FX liquidity and execution services.", regions: ["Global"], categories: ["fx"], capabilities: ["Bank liquidity", "API execution", "FX"]},
  {id: "b2c2", name: "B2C2", url: "https://www.b2c2.com/", kind: "Digital-asset liquidity", summary: "Institutional crypto and stablecoin liquidity, execution and OTC services.", regions: ["Global"], categories: ["fx", "stablecoins"], capabilities: ["Liquidity", "OTC", "Stablecoins"]},
  {id: "gsr", name: "GSR", url: "https://www.gsr.io/", kind: "Digital-asset liquidity", summary: "Market making, OTC liquidity and trading services for digital assets.", regions: ["Global"], categories: ["fx", "stablecoins"], capabilities: ["Market making", "OTC", "Liquidity"]},
  {id: "wintermute", name: "Wintermute", url: "https://www.wintermute.com/", kind: "Digital-asset liquidity", summary: "Algorithmic liquidity, OTC trading and market-making services.", regions: ["Global"], categories: ["fx", "stablecoins"], capabilities: ["Market making", "OTC", "Liquidity"]},
  {id: "keyrock", name: "Keyrock", url: "https://keyrock.com/", kind: "Digital-asset liquidity", summary: "Market making, OTC execution and liquidity services for digital assets.", regions: ["Global"], categories: ["fx", "stablecoins"], capabilities: ["Market making", "OTC", "Liquidity"]},
  {id: "kaiko", name: "Kaiko", url: "https://www.kaiko.com/", kind: "Market data", summary: "Institutional crypto market data, pricing, indices and analytics.", regions: ["Global"], categories: ["fx"], capabilities: ["Market data", "Pricing", "Indices"]},
  {id: "coin-metrics", name: "Coin Metrics", url: "https://coinmetrics.io/", kind: "Market data", summary: "Network data, market data, reference rates and institutional digital-asset analytics.", regions: ["Global"], categories: ["fx"], capabilities: ["Reference rates", "Market data", "Network data"]},
  {id: "chainlink", name: "Chainlink", url: "https://chain.link/", kind: "Oracle network", summary: "Decentralised data feeds and cross-chain infrastructure for onchain financial applications.", regions: ["Global"], categories: ["fx", "stablecoins"], capabilities: ["Price feeds", "Proof of reserve", "Cross-chain"]},
  {id: "plaid", name: "Plaid", url: "https://plaid.com/", kind: "Open banking", summary: "Account linking, verification, balances, transactions and payment initiation infrastructure.", regions: ["US", "Canada", "Europe"], categories: ["openbanking"], capabilities: ["Account linking", "Verification", "Transactions"], featured: true},
  {id: "tink", name: "Tink", url: "https://tink.com/", kind: "Open banking", summary: "European account data, payment initiation and financial-data infrastructure.", regions: ["Europe"], categories: ["openbanking"], capabilities: ["Account data", "Payments", "Verification"]},
  {id: "truelayer", name: "TrueLayer", url: "https://truelayer.com/", kind: "Open banking", summary: "Pay-by-bank, account data and payment infrastructure across open-banking markets.", regions: ["UK", "Europe"], categories: ["openbanking", "rails"], capabilities: ["Pay by bank", "Account data", "Payments"]},
];
