import type { Provider } from "./types";

type Listing = Omit<
  Provider,
  "relationshipStatus" | "technicalStatus" | "asOf"
> &
  Partial<Pick<Provider, "technicalStatus">>;
const listed = (provider: Listing): Provider => ({
  ...provider,
  relationshipStatus: "No relationship claimed",
  technicalStatus: provider.technicalStatus ?? "Link only",
  asOf: "2026-08-20",
});

export const PROVIDERS: Provider[] = [
  // Sponsor banks and embedded banking
  listed({
    id: "column",
    name: "Column",
    url: "https://column.com/",
    docsUrl: "https://docs.column.com/",
    kind: "Sponsor bank",
    provides: "US accounts, ACH, wires and bank ledger services.",
    regions: ["US"],
    categories: ["sponsor", "accounts", "rails"],
    capabilities: ["Accounts", "ACH & wires", "Ledger"],
    modules: ["Accounts", "Receiving details", "Transfers", "Ledger"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "clearbank",
    name: "ClearBank",
    url: "https://clear.bank/",
    docsUrl: "https://clearbank.github.io/uk/docs/embedded-banking/",
    kind: "Clearing bank",
    provides: "UK and European embedded accounts, clearing and payments.",
    regions: ["UK", "Europe"],
    categories: ["sponsor", "accounts", "rails"],
    capabilities: ["Accounts", "Clearing", "Payments"],
    modules: ["Onboarding", "Accounts", "Receiving details", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "griffin",
    name: "Griffin",
    url: "https://griffin.com/",
    docsUrl: "https://docs.griffin.com/api/",
    kind: "Banking platform",
    provides: "UK bank accounts, onboarding and payments.",
    regions: ["UK"],
    categories: ["sponsor", "accounts", "rails"],
    capabilities: ["Onboarding", "Accounts", "Payments"],
    modules: ["Customers", "Applications", "Accounts", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "swan",
    name: "Swan",
    url: "https://www.swan.io/",
    docsUrl: "https://docs.swan.io/developers/",
    kind: "Embedded banking",
    provides: "European accounts, cards and payments.",
    regions: ["Europe"],
    categories: ["sponsor", "accounts", "cards", "rails"],
    capabilities: ["Accounts", "Cards", "Payments"],
    modules: ["Onboarding", "Accounts", "Cards", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "unit",
    name: "Unit",
    url: "https://www.unit.co/",
    docsUrl: "https://docs.unit.co/",
    kind: "Banking platform",
    provides: "US account, card and payment programme infrastructure.",
    regions: ["US"],
    categories: ["sponsor", "accounts", "cards", "rails"],
    capabilities: ["Accounts", "Cards", "Payments"],
    modules: ["Customers", "Accounts", "Cards", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "treasury-prime",
    name: "Treasury Prime",
    url: "https://www.treasuryprime.com/",
    docsUrl: "https://docs.treasuryprime.com/reference/introduction",
    kind: "Banking platform",
    provides: "US bank-network accounts and payment rails.",
    regions: ["US"],
    categories: ["sponsor", "accounts", "rails"],
    capabilities: ["Accounts", "Bank network", "Payments"],
    modules: ["Customers", "Accounts", "Receiving details", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "synctera",
    name: "Synctera",
    url: "https://synctera.com/",
    docsUrl: "https://docs.synctera.com/home",
    kind: "Banking platform",
    provides: "US accounts, cards, ACH and compliance workflows.",
    regions: ["US"],
    categories: ["sponsor", "accounts", "cards", "rails", "compliance"],
    capabilities: ["Accounts", "Cards", "ACH"],
    modules: ["Onboarding", "Accounts", "Cards", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "increase",
    name: "Increase",
    url: "https://increase.com/",
    docsUrl: "https://bnk.dev/",
    kind: "Banking platform",
    provides: "US accounts, ACH, wires, cards and real-time payments.",
    regions: ["US"],
    categories: ["sponsor", "accounts", "rails", "cards"],
    capabilities: ["Accounts", "Payments", "Cards"],
    modules: ["Accounts", "Receiving details", "Transfers", "Cards"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),

  // Accounts, payments and cross-border rails
  listed({
    id: "currencycloud",
    name: "Currencycloud",
    url: "https://www.currencycloud.com/",
    docsUrl: "https://developer.currencycloud.com/",
    kind: "Cross-border platform",
    provides:
      "Multi-currency balances, collections, beneficiaries, FX and payouts.",
    regions: ["Global"],
    categories: ["accounts", "rails", "fx"],
    capabilities: ["Balances", "Payments", "FX"],
    modules: ["Accounts", "Recipients", "Destinations", "Quotes", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "nium",
    name: "Nium",
    url: "https://www.nium.com/",
    docsUrl: "https://docs.nium.com/",
    kind: "Payments platform",
    provides: "Global accounts, payouts and card issuing.",
    regions: ["Global"],
    categories: ["accounts", "rails", "cards"],
    capabilities: ["Accounts", "Payouts", "Cards"],
    modules: [
      "Accounts",
      "Receiving details",
      "Recipients",
      "Transfers",
      "Cards",
    ],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "modulr",
    name: "Modulr",
    url: "https://www.modulrfinance.com/",
    docsUrl: "https://modulr.readme.io/",
    kind: "Embedded payments",
    provides: "UK and European accounts, payment initiation and payouts.",
    regions: ["UK", "Europe"],
    categories: ["accounts", "rails"],
    capabilities: ["Accounts", "Payments", "Payouts"],
    modules: ["Accounts", "Receiving details", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "openpayd",
    name: "OpenPayd",
    url: "https://www.openpayd.com/",
    docsUrl: "https://www.openpayd.com/api/",
    kind: "Embedded finance",
    provides: "Virtual IBANs, multi-currency accounts, payments and FX.",
    regions: ["UK", "Europe"],
    categories: ["accounts", "rails", "fx"],
    capabilities: ["Virtual IBANs", "Payments", "FX"],
    modules: ["Accounts", "Receiving details", "Transfers", "Quotes"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "thunes",
    name: "Thunes",
    url: "https://www.thunes.com/",
    docsUrl: "https://docs.thunes.com/",
    kind: "Payments network",
    provides: "Cross-border payouts to bank accounts and wallets.",
    regions: ["Global"],
    categories: ["rails"],
    capabilities: ["Payouts", "Bank accounts", "Wallets"],
    modules: ["Recipients", "Destinations", "Transfers", "Rails"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "dlocal",
    name: "dLocal",
    url: "https://www.dlocal.com/",
    docsUrl: "https://docs.dlocal.com/",
    kind: "Local payments",
    provides: "Local pay-ins and payouts across emerging markets.",
    regions: ["LATAM", "Africa", "APAC"],
    categories: ["rails"],
    capabilities: ["Pay-ins", "Payouts", "Local methods"],
    modules: ["Destinations", "Transfers", "Payment links"],
    access: "Commercial partner",
    sandbox: "Available",
  }),

  // Identity, fraud and financial crime
  listed({
    id: "sumsub",
    name: "Sumsub",
    url: "https://sumsub.com/",
    docsUrl: "https://docs.sumsub.com/reference",
    kind: "Identity and risk",
    provides: "KYC, KYB, document checks, monitoring and case tooling.",
    regions: ["Global"],
    categories: ["compliance"],
    capabilities: ["KYC & KYB", "Monitoring", "Cases"],
    modules: ["Applications", "Documents", "Decisions", "Events"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "persona",
    name: "Persona",
    url: "https://withpersona.com/",
    docsUrl: "https://docs.withpersona.com/",
    kind: "Identity verification",
    provides: "Configurable identity and business-verification workflows.",
    regions: ["Global"],
    categories: ["compliance"],
    capabilities: ["Identity", "KYB", "Workflows"],
    modules: ["Applications", "Documents", "Decisions"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "alloy",
    name: "Alloy",
    url: "https://www.alloy.com/",
    docsUrl: "https://developer.alloy.com/",
    kind: "Identity decisioning",
    provides: "Identity, fraud and onboarding decision orchestration.",
    regions: ["US", "Global"],
    categories: ["compliance"],
    capabilities: ["Decisioning", "Identity", "Fraud"],
    modules: ["Applications", "Attestations", "Decisions"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "trulioo",
    name: "Trulioo",
    url: "https://www.trulioo.com/",
    docsUrl: "https://developer.trulioo.com/",
    kind: "Identity verification",
    provides: "Global person and business verification APIs.",
    regions: ["Global"],
    categories: ["compliance"],
    capabilities: ["KYC", "KYB", "Identity data"],
    modules: ["Applications", "Documents", "Decisions"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "complyadvantage",
    name: "ComplyAdvantage",
    url: "https://complyadvantage.com/",
    docsUrl: "https://docs.complyadvantage.com/",
    kind: "Financial crime",
    provides: "Sanctions, PEP, adverse-media and transaction screening.",
    regions: ["Global"],
    categories: ["compliance"],
    capabilities: ["Sanctions", "PEP", "Monitoring"],
    modules: ["Applications", "Attestations", "Events"],
    access: "Commercial partner",
    sandbox: "Not listed",
  }),
  listed({
    id: "chainalysis",
    name: "Chainalysis",
    url: "https://www.chainalysis.com/",
    docsUrl: "https://docs.chainalysis.com/",
    kind: "Blockchain intelligence",
    provides: "Wallet screening and digital-asset transaction monitoring.",
    regions: ["Global"],
    categories: ["compliance", "stablecoins"],
    capabilities: ["Wallet screening", "Monitoring", "Investigations"],
    modules: ["Wallets", "Transfers", "Applications"],
    access: "Institutional",
    sandbox: "Not listed",
  }),
  listed({
    id: "trm-labs",
    name: "TRM Labs",
    url: "https://www.trmlabs.com/",
    docsUrl: "https://docs.trmlabs.com/",
    kind: "Blockchain intelligence",
    provides: "Wallet screening and digital-asset transaction monitoring.",
    regions: ["Global"],
    categories: ["compliance", "stablecoins"],
    capabilities: ["Wallet screening", "Monitoring", "Risk data"],
    modules: ["Wallets", "Transfers", "Applications"],
    access: "Institutional",
    sandbox: "Not listed",
  }),

  // Stablecoin payments and ramps
  listed({
    id: "bvnk",
    name: "BVNK",
    url: "https://www.bvnk.com/",
    docsUrl: "https://docs.bvnk.com/bvnk/api-explorer/api-overview/overview/",
    kind: "Stablecoin payments",
    provides:
      "Fiat and stablecoin wallets, payment channels, conversion and payouts.",
    regions: ["Global"],
    categories: ["stablecoins", "accounts", "rails", "fx"],
    capabilities: ["Wallets", "Conversion", "Payouts"],
    modules: ["Wallets", "Accounts", "Quotes", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "bridge",
    name: "Bridge",
    url: "https://www.bridge.xyz/",
    docsUrl: "https://apidocs.bridge.xyz/",
    kind: "Stablecoin orchestration",
    provides: "Virtual accounts, stablecoin conversion and payouts.",
    regions: ["Global"],
    categories: ["stablecoins", "accounts", "rails", "fx"],
    capabilities: ["Virtual accounts", "Conversion", "Payouts"],
    modules: ["Wallets", "Receiving details", "Quotes", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
    technicalStatus: "Included descriptor",
  }),
  listed({
    id: "dakota",
    name: "Dakota",
    url: "https://www.dakota.xyz/",
    docsUrl: "https://docs.dakota.xyz/",
    kind: "Stablecoin business infrastructure",
    provides:
      "Stablecoin-backed business accounts, wallets, ramps and global money movement.",
    regions: ["Global"],
    categories: ["stablecoins", "accounts", "rails", "custody"],
    capabilities: ["Business accounts", "Wallets", "On/off ramps", "Transfers"],
    modules: [
      "Customers",
      "Accounts",
      "Wallets",
      "Receiving details",
      "Transfers",
    ],
    access: "Commercial partner",
    sandbox: "Gated",
    technicalStatus: "Included descriptor",
  }),
  listed({
    id: "circle",
    name: "Circle",
    url: "https://www.circle.com/",
    docsUrl: "https://developers.circle.com/api-reference",
    kind: "Stablecoin infrastructure",
    provides: "USDC and EURC wallets, minting, redemption and transfers.",
    regions: ["Global"],
    categories: ["stablecoins", "custody", "rails"],
    capabilities: ["USDC & EURC", "Wallets", "Transfers"],
    modules: ["Wallets", "Assets", "Transfers", "Quotes"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "zero-hash",
    name: "Zero Hash",
    url: "https://zerohash.com/",
    docsUrl: "https://docs.zerohash.com/",
    kind: "Crypto infrastructure",
    provides:
      "Embedded crypto and stablecoin accounts, custody, conversion and movement.",
    regions: ["Global"],
    categories: ["stablecoins", "custody", "rails", "fx"],
    capabilities: ["Stablecoins", "Custody", "Conversion"],
    modules: ["Wallets", "Assets", "Quotes", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "transak",
    name: "Transak",
    url: "https://transak.com/",
    docsUrl: "https://docs.transak.com/",
    kind: "On/off ramp",
    provides: "Embedded fiat-to-crypto and crypto-to-fiat ramps.",
    regions: ["Global"],
    categories: ["stablecoins", "rails"],
    capabilities: ["On-ramp", "Off-ramp", "Local methods"],
    modules: ["Payment links", "Wallets", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "ramp-network",
    name: "Ramp Network",
    url: "https://ramp.network/",
    docsUrl: "https://docs.ramp.network/",
    kind: "On/off ramp",
    provides: "Embedded on/off-ramp APIs and widgets.",
    regions: ["Global"],
    categories: ["stablecoins", "rails"],
    capabilities: ["On-ramp", "Off-ramp", "Widgets"],
    modules: ["Payment links", "Wallets", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),

  // Wallet and custody infrastructure
  listed({
    id: "fireblocks",
    name: "Fireblocks",
    url: "https://www.fireblocks.com/",
    docsUrl: "https://api-reference.fireblocks.com/",
    kind: "Wallet and custody",
    provides:
      "Institutional wallets, policy controls and transaction orchestration.",
    regions: ["Global"],
    categories: ["custody", "stablecoins"],
    capabilities: ["Wallets", "Policies", "Orchestration"],
    modules: ["Wallets", "Policies", "Approvals", "Transfers"],
    access: "Institutional",
    sandbox: "Available",
  }),
  listed({
    id: "bitgo",
    name: "BitGo",
    url: "https://www.bitgo.com/",
    docsUrl: "https://developers.bitgo.com/",
    kind: "Wallet and custody",
    provides:
      "Custodial and self-managed wallets, transfers and policy controls.",
    regions: ["Global"],
    categories: ["custody", "stablecoins"],
    capabilities: ["Custody", "Wallets", "Policies"],
    modules: ["Wallets", "Policies", "Transfers"],
    access: "Institutional",
    sandbox: "Available",
  }),
  listed({
    id: "anchorage",
    name: "Anchorage Digital",
    url: "https://www.anchorage.com/",
    docsUrl: "https://www.anchorage.com/platform",
    kind: "Institutional custody",
    provides: "Institutional custody and settlement services.",
    regions: ["US", "Global"],
    categories: ["custody", "stablecoins"],
    capabilities: ["Custody", "Settlement", "Institutional access"],
    modules: ["Wallets", "Transfers", "Attestations"],
    access: "Institutional",
    sandbox: "Not listed",
  }),
  listed({
    id: "dfns",
    name: "Dfns",
    url: "https://www.dfns.co/",
    docsUrl: "https://docs.dfns.co/",
    kind: "Wallet infrastructure",
    provides: "Wallet creation, signing and policy APIs.",
    regions: ["Global"],
    categories: ["custody"],
    capabilities: ["Wallet APIs", "Signing", "Policies"],
    modules: ["Wallets", "Policies", "Approvals"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "turnkey",
    name: "Turnkey",
    url: "https://www.turnkey.com/",
    docsUrl: "https://docs.turnkey.com/",
    kind: "Wallet infrastructure",
    provides: "Embedded wallets, signing and policy infrastructure.",
    regions: ["Global"],
    categories: ["custody"],
    capabilities: ["Wallets", "Signing", "Policies"],
    modules: ["Wallets", "Policies", "Approvals"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),

  // Card issuing and processing
  listed({
    id: "lithic",
    name: "Lithic",
    url: "https://www.lithic.com/",
    docsUrl: "https://docs.lithic.com/",
    kind: "Card issuing",
    provides: "Card issuing, controls, authorisations and transactions.",
    regions: ["US"],
    categories: ["cards"],
    capabilities: ["Issuing", "Controls", "Authorisations"],
    modules: ["Cards", "Controls", "Authorisations", "Statements"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "marqeta",
    name: "Marqeta",
    url: "https://www.marqeta.com/",
    docsUrl:
      "https://www.marqeta.com/docs/developer-guides/core-api-quick-start",
    kind: "Card issuing",
    provides: "Card products, issuing, processing and authorisation controls.",
    regions: ["Global"],
    categories: ["cards"],
    capabilities: ["Issuing", "Processing", "Controls"],
    modules: ["Cards", "Authorisations", "Transactions"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "stripe-issuing",
    name: "Stripe Issuing",
    url: "https://stripe.com/issuing",
    docsUrl: "https://docs.stripe.com/issuing",
    kind: "Card issuing",
    provides: "Virtual and physical cards, controls and authorisations.",
    regions: ["Multi-region"],
    categories: ["cards"],
    capabilities: ["Cards", "Controls", "Authorisations"],
    modules: ["Cards", "Controls", "Authorisations"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "adyen-issuing",
    name: "Adyen Issuing",
    url: "https://www.adyen.com/issuing",
    docsUrl: "https://docs.adyen.com/issuing/",
    kind: "Card issuing",
    provides: "Card issuing and processing within Adyen programmes.",
    regions: ["Global"],
    categories: ["cards"],
    capabilities: ["Issuing", "Processing", "Transactions"],
    modules: ["Cards", "Authorisations", "Transactions"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "highnote",
    name: "Highnote",
    url: "https://highnote.com/",
    docsUrl: "https://docs.highnote.com/",
    kind: "Card platform",
    provides: "Card programmes, issuing, ledger and payment processing.",
    regions: ["US"],
    categories: ["cards", "operations"],
    capabilities: ["Issuing", "Ledger", "Processing"],
    modules: ["Cards", "Ledger", "Authorisations"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "enfuce",
    name: "Enfuce",
    url: "https://enfuce.com/",
    docsUrl: "https://docs.enfuce.com/",
    kind: "Card processing",
    provides: "European card issuing and processing.",
    regions: ["Europe"],
    categories: ["cards"],
    capabilities: ["Issuing", "Processing", "Transactions"],
    modules: ["Cards", "Authorisations", "Transactions"],
    access: "Commercial partner",
    sandbox: "Available",
  }),

  // FX liquidity and market data
  listed({
    id: "lmax",
    name: "LMAX Group",
    url: "https://www.lmax.com/",
    docsUrl: "https://docs.lmax.com/",
    kind: "Trading venue",
    provides: "Institutional FX and digital-asset market data and execution.",
    regions: ["Global"],
    categories: ["fx"],
    capabilities: ["Market data", "Liquidity", "Execution"],
    modules: ["FX reference sources", "Quotes", "Source adapters"],
    access: "Institutional",
    sandbox: "Available",
  }),
  listed({
    id: "fxspotstream",
    name: "FXSpotStream",
    url: "https://www.fxspotstream.com/",
    docsUrl: "https://www.fxspotstream.com/services/",
    kind: "FX liquidity network",
    provides: "Aggregated institutional bank FX liquidity through one API.",
    regions: ["Global"],
    categories: ["fx"],
    capabilities: ["Bank liquidity", "API execution", "FX"],
    modules: ["FX source adapters", "Quotes", "Execution"],
    access: "Institutional",
    sandbox: "Not listed",
  }),
  listed({
    id: "b2c2",
    name: "B2C2",
    url: "https://www.b2c2.com/",
    docsUrl: "https://www.b2c2.com/products/api/",
    kind: "Digital-asset liquidity",
    provides: "Institutional crypto and stablecoin OTC liquidity.",
    regions: ["Global"],
    categories: ["fx", "stablecoins"],
    capabilities: ["OTC", "Liquidity", "Stablecoins"],
    modules: ["FX source adapters", "Quotes", "Execution"],
    access: "Institutional",
    sandbox: "Not listed",
  }),
  listed({
    id: "kaiko",
    name: "Kaiko",
    url: "https://www.kaiko.com/",
    docsUrl: "https://docs.kaiko.com/",
    kind: "Market data",
    provides: "Institutional crypto market data, order books and pricing.",
    regions: ["Global"],
    categories: ["fx"],
    capabilities: ["Market data", "Order books", "Pricing"],
    modules: ["FX reference prices", "Market data"],
    access: "Commercial partner",
    sandbox: "Not offered",
  }),
  listed({
    id: "coin-metrics",
    name: "Coin Metrics",
    url: "https://coinmetrics.io/",
    docsUrl: "https://docs.coinmetrics.io/",
    kind: "Market data",
    provides: "Digital-asset market and network data and reference rates.",
    regions: ["Global"],
    categories: ["fx"],
    capabilities: ["Reference rates", "Market data", "Network data"],
    modules: ["FX reference prices", "Asset data"],
    access: "Self-serve → partner",
    sandbox: "Not offered",
  }),

  // Open banking and account connectivity
  listed({
    id: "plaid",
    name: "Plaid",
    url: "https://plaid.com/",
    docsUrl: "https://plaid.com/docs/",
    kind: "Open banking",
    provides: "Account linking, balances, transactions and verification.",
    regions: ["US", "Canada", "Europe"],
    categories: ["openbanking"],
    capabilities: ["Account linking", "Transactions", "Verification"],
    modules: ["Linked accounts", "Name checks", "Account data"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "tink",
    name: "Tink",
    url: "https://tink.com/",
    docsUrl: "https://console.tink.com/",
    kind: "Open banking",
    provides: "European account data, verification and payment initiation.",
    regions: ["Europe"],
    categories: ["openbanking", "rails"],
    capabilities: ["Account data", "Verification", "Payments"],
    modules: ["Linked accounts", "Account data", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "truelayer",
    name: "TrueLayer",
    url: "https://truelayer.com/",
    docsUrl: "https://docs.truelayer.com/",
    kind: "Open banking",
    provides: "Pay-by-bank, account data and payment initiation.",
    regions: ["UK", "Europe"],
    categories: ["openbanking", "rails"],
    capabilities: ["Pay by bank", "Account data", "Payments"],
    modules: ["Linked accounts", "Destinations", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "yapily",
    name: "Yapily",
    url: "https://www.yapily.com/",
    docsUrl: "https://docs.yapily.com/",
    kind: "Open banking",
    provides:
      "European account-information and payment-initiation connectivity.",
    regions: ["UK", "Europe"],
    categories: ["openbanking", "rails"],
    capabilities: ["Account data", "Payments", "Connectivity"],
    modules: ["Linked accounts", "Account data", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "mx",
    name: "MX",
    url: "https://www.mx.com/",
    docsUrl: "https://docs.mx.com/",
    kind: "Open finance",
    provides: "North American account connectivity and data enrichment.",
    regions: ["US", "Canada"],
    categories: ["openbanking"],
    capabilities: ["Account data", "Verification", "Enrichment"],
    modules: ["Linked accounts", "Account data", "Verification"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "belvo",
    name: "Belvo",
    url: "https://belvo.com/",
    docsUrl: "https://developers.belvo.com/",
    kind: "Open finance",
    provides: "Latin American open-finance data and payment initiation.",
    regions: ["LATAM"],
    categories: ["openbanking", "rails"],
    capabilities: ["Account data", "Payments", "Open finance"],
    modules: ["Linked accounts", "Account data", "Transfers"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "brankas",
    name: "Brankas",
    url: "https://www.brankas.com/",
    docsUrl: "https://docs.brankas.com/",
    kind: "Open finance",
    provides: "Southeast Asian bank-data and payment connectivity.",
    regions: ["Southeast Asia"],
    categories: ["openbanking", "rails"],
    capabilities: ["Bank data", "Payments", "Regional connectivity"],
    modules: ["Linked accounts", "Account data", "Transfers"],
    access: "Commercial partner",
    sandbox: "Available",
  }),

  // Ledger, reconciliation and operations
  listed({
    id: "modern-treasury",
    name: "Modern Treasury",
    url: "https://www.moderntreasury.com/",
    docsUrl:
      "https://docs.moderntreasury.com/platform/reference/getting-started",
    kind: "Payment operations",
    provides:
      "Payment operations, bank connectivity, ledger and reconciliation.",
    regions: ["US", "Global"],
    categories: ["operations", "rails"],
    capabilities: ["Payments", "Ledger", "Reconciliation"],
    modules: ["Transfers", "Ledger", "Reconciliation", "Events"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "formance",
    name: "Formance",
    url: "https://www.formance.com/",
    docsUrl: "https://docs.formance.com/",
    kind: "Ledger infrastructure",
    provides:
      "Open-source ledger, payment flows, connectivity and reconciliation.",
    regions: ["Global"],
    categories: ["operations"],
    capabilities: ["Ledger", "Flows", "Reconciliation"],
    modules: ["Ledger", "Transfers", "Reconciliation"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
  listed({
    id: "fragment",
    name: "Fragment",
    url: "https://fragment.dev/",
    docsUrl: "https://fragment.dev/docs",
    kind: "Ledger infrastructure",
    provides: "Double-entry ledger APIs for financial events.",
    regions: ["Global"],
    categories: ["operations"],
    capabilities: ["Ledger", "Balances", "Accounting"],
    modules: ["Ledger", "Balances", "Statements"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "hummingbird",
    name: "Hummingbird",
    url: "https://www.hummingbird.co/",
    docsUrl:
      "https://help.hummingbird.co/general/what-are-the-hummingbird-apis",
    kind: "Compliance operations",
    provides: "Compliance alerts, cases and regulatory filing workflows.",
    regions: ["Global"],
    categories: ["operations", "compliance"],
    capabilities: ["Cases", "Investigations", "Reporting"],
    modules: ["Applications", "Cases", "Events"],
    access: "Commercial partner",
    sandbox: "Available",
  }),
  listed({
    id: "vgs",
    name: "VGS",
    url: "https://www.verygoodsecurity.com/",
    docsUrl: "https://www.verygoodsecurity.com/docs/",
    kind: "Data security",
    provides: "Tokenisation and vaulting for card and identity data.",
    regions: ["Global"],
    categories: ["operations", "cards"],
    capabilities: ["Vaulting", "Tokenisation", "Data security"],
    modules: ["Cards", "Receiving details", "Documents"],
    access: "Self-serve → partner",
    sandbox: "Available",
  }),
];
