import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "yapily", name: "Yapily", url: "https://www.yapily.com/", kind: "Open banking", summary: "Open-banking connectivity for account data and payment initiation.", regions: ["UK", "Europe"], categories: ["openbanking"], capabilities: ["Account data", "Payments", "Connectivity"]},
  {id: "mastercard-open-banking", name: "Mastercard Open Banking", url: "https://www.mastercard.com/global/en/business/open-finance.html", kind: "Open banking", summary: "Account connectivity, verification and open-finance services through Mastercard.", regions: ["US", "Europe", "Global"], categories: ["openbanking"], capabilities: ["Account verification", "Open finance", "Data"]},
  {id: "mx", name: "MX", url: "https://www.mx.com/", kind: "Open finance", summary: "Account connectivity, financial data, verification and money-experience infrastructure.", regions: ["US", "Canada"], categories: ["openbanking"], capabilities: ["Account data", "Verification", "Data enrichment"]},
  {id: "akoya", name: "Akoya", url: "https://akoya.com/", kind: "Open banking", summary: "API network for consumer-permissioned financial data sharing.", regions: ["US"], categories: ["openbanking"], capabilities: ["Financial data", "API network", "Consumer permissions"]},
  {id: "flinks", name: "Flinks", url: "https://flinks.com/", kind: "Open banking", summary: "Account connectivity, verification and financial-data products for North America.", regions: ["Canada", "US"], categories: ["openbanking"], capabilities: ["Account verification", "Data", "Connectivity"]},
  {id: "belvo", name: "Belvo", url: "https://belvo.com/", kind: "Open finance", summary: "Open-finance data and payment infrastructure focused on Latin America.", regions: ["LATAM"], categories: ["openbanking", "rails"], capabilities: ["Account data", "Payments", "Open finance"]},
  {id: "salt-edge", name: "Salt Edge", url: "https://www.saltedge.com/", kind: "Open banking", summary: "Global bank connectivity, account information, payments and compliance tooling.", regions: ["Europe", "Global"], categories: ["openbanking"], capabilities: ["Bank connectivity", "Account data", "Payments"]},
  {id: "brankas", name: "Brankas", url: "https://www.brankas.com/", kind: "Open finance", summary: "Bank-data and payment connectivity for Southeast Asian markets.", regions: ["Southeast Asia"], categories: ["openbanking", "rails"], capabilities: ["Bank data", "Payments", "Regional connectivity"]},
  {id: "mono", name: "Mono", url: "https://mono.co/", kind: "Open finance", summary: "Account data, identity and payment connectivity for African financial products.", regions: ["Africa"], categories: ["openbanking", "rails"], capabilities: ["Account data", "Payments", "Identity"]},
  {id: "modern-treasury", name: "Modern Treasury", url: "https://www.moderntreasury.com/", kind: "Payment operations", summary: "Payment operations, bank connectivity, reconciliation and ledger workflows.", regions: ["US", "Global"], categories: ["operations", "rails"], capabilities: ["Payment operations", "Reconciliation", "Bank connectivity"], featured: true},
  {id: "numeral", name: "Numeral", url: "https://www.numeral.io/", kind: "Payment operations", summary: "Payment operations, bank connectivity and reconciliation infrastructure for fintechs.", regions: ["Europe", "Global"], categories: ["operations", "rails"], capabilities: ["Bank connectivity", "Payments", "Reconciliation"]},
  {id: "formance", name: "Formance", url: "https://www.formance.com/", kind: "Ledger infrastructure", summary: "Open-source ledger and payment-orchestration infrastructure for financial products.", regions: ["Global"], categories: ["operations"], capabilities: ["Ledger", "Orchestration", "Reconciliation"]},
];
