import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "bvnk", name: "BVNK", url: "https://www.bvnk.com/", kind: "Stablecoin payments", summary: "Stablecoin and fiat payments, wallets, conversion and payouts for businesses and platforms.", regions: ["Global"], categories: ["rails", "stablecoins", "accounts", "fx", "cards"], capabilities: ["Stablecoin payments", "Wallets", "Conversion"], featured: true},
  {id: "bridge", name: "Bridge", url: "https://www.bridge.xyz/", kind: "Stablecoin infrastructure", summary: "Stablecoin orchestration for conversion, payments, wallets and cross-border movement.", regions: ["Global"], categories: ["rails", "stablecoins"], capabilities: ["Stablecoin rails", "Conversion", "Payments"], featured: true},
  {id: "circle", name: "Circle", url: "https://www.circle.com/", kind: "Stablecoin issuer", summary: "USDC and EURC infrastructure, minting, redemption, wallets, cross-chain transfer and payment APIs.", regions: ["Global"], categories: ["stablecoins", "fx", "custody"], capabilities: ["USDC & EURC", "Mint & redeem", "Wallet APIs"], featured: true},
  {id: "paxos", name: "Paxos", url: "https://paxos.com/", kind: "Stablecoin issuer", summary: "Regulated stablecoin, tokenisation and crypto infrastructure for financial institutions.", regions: ["Global"], categories: ["stablecoins"], capabilities: ["Stablecoin issuance", "Tokenisation", "Settlement"]},
  {id: "zero-hash", name: "Zero Hash", url: "https://zerohash.com/", kind: "Regulated crypto infrastructure", summary: "APIs for stablecoins, crypto, custody, conversion and money movement inside fintech products.", regions: ["Global"], categories: ["stablecoins", "custody", "rails"], capabilities: ["On/off ramps", "Custody", "Stablecoins"]},
  {id: "dakota", name: "Dakota", url: "https://www.dakota.xyz/", kind: "Stablecoin banking", summary: "Business accounts, stablecoin wallets, money movement and conversion through one platform.", regions: ["Global"], categories: ["accounts", "rails", "stablecoins", "custody"], capabilities: ["Business accounts", "Wallets", "Stablecoin payments"], featured: true},
  {id: "brale", name: "Brale", url: "https://brale.xyz/", kind: "Stablecoin issuance", summary: "Stablecoin issuance and orchestration infrastructure for companies launching tokenised money.", regions: ["US", "Global"], categories: ["stablecoins"], capabilities: ["Issuance", "Mint & redeem", "Branded stablecoins"]},
  {id: "m0", name: "M0", url: "https://www.m0.org/", kind: "Stablecoin infrastructure", summary: "Protocol and tooling for builders issuing programmable, interoperable stablecoins.", regions: ["Global"], categories: ["stablecoins"], capabilities: ["Issuance infrastructure", "Programmability", "Interoperability"]},
  {id: "transak", name: "Transak", url: "https://transak.com/", kind: "On/off ramp", summary: "Fiat-to-crypto and crypto-to-fiat infrastructure embedded through APIs and widgets.", regions: ["Global"], categories: ["stablecoins", "rails"], capabilities: ["On-ramp", "Off-ramp", "Local methods"]},
  {id: "moonpay", name: "MoonPay", url: "https://www.moonpay.com/", kind: "On/off ramp", summary: "Consumer and embedded fiat-to-crypto infrastructure, payments and wallet tooling.", regions: ["Global"], categories: ["stablecoins", "rails"], capabilities: ["On-ramp", "Off-ramp", "Payments"]},
  {id: "ramp-network", name: "Ramp Network", url: "https://ramp.network/", kind: "On/off ramp", summary: "Embedded fiat-to-crypto and crypto-to-fiat conversion across local payment methods.", regions: ["Global"], categories: ["stablecoins", "rails"], capabilities: ["On-ramp", "Off-ramp", "Local rails"]},
  {id: "fireblocks", name: "Fireblocks", url: "https://www.fireblocks.com/", kind: "Wallet & custody", summary: "Institutional wallet, custody, settlement-network and policy infrastructure for digital assets.", regions: ["Global"], categories: ["custody", "stablecoins"], capabilities: ["MPC wallets", "Policy engine", "Settlement network"], featured: true},
];
