import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "column", name: "Column", url: "https://column.com/", kind: "Bank", summary: "Direct US banking APIs for accounts, ACH, wires, realtime payments and card programmes.", regions: ["US"], categories: ["sponsor", "accounts", "rails", "cards"], capabilities: ["Bank accounts", "ACH & wires", "Realtime payments"], featured: true},
  {id: "lead-bank", name: "Lead Bank", url: "https://lead.bank/", kind: "Bank", summary: "US sponsor-bank infrastructure for fintech and embedded financial products.", regions: ["US"], categories: ["sponsor", "accounts", "rails"], capabilities: ["Sponsor banking", "Accounts", "Payments"]},
  {id: "cross-river", name: "Cross River", url: "https://www.crossriver.com/", kind: "Bank", summary: "Regulated US banking, payments, card and lending infrastructure for fintech platforms.", regions: ["US"], categories: ["sponsor", "accounts", "rails", "cards"], capabilities: ["Banking APIs", "Payments", "Card programmes"]},
  {id: "clearbank", name: "ClearBank", url: "https://clear.bank/", kind: "Bank", summary: "API-first UK and European banking, clearing, virtual accounts, payments and multi-currency infrastructure.", regions: ["UK", "Europe"], categories: ["sponsor", "accounts", "rails", "fx"], capabilities: ["Virtual accounts", "Clearing", "Payments"], featured: true},
  {id: "griffin", name: "Griffin", url: "https://griffin.com/", kind: "Bank", summary: "API-first UK bank for embedded accounts, payments and financial-crime controls.", regions: ["UK"], categories: ["sponsor", "accounts", "rails", "compliance"], capabilities: ["Bank accounts", "Payments", "Compliance"]},
  {id: "banking-circle", name: "Banking Circle", url: "https://www.bankingcircle.com/", kind: "Bank", summary: "Banking, clearing, virtual accounts and cross-border payment infrastructure for financial businesses.", regions: ["Europe", "Global"], categories: ["sponsor", "accounts", "rails", "fx"], capabilities: ["Virtual accounts", "Cross-border payments", "FX"]},
  {id: "solaris", name: "Solaris", url: "https://www.solarisgroup.com/", kind: "Banking platform", summary: "European embedded-finance infrastructure spanning accounts, cards, payments and compliance services.", regions: ["Europe"], categories: ["sponsor", "accounts", "cards"], capabilities: ["Accounts", "Cards", "Embedded finance"]},
  {id: "swan", name: "Swan", url: "https://www.swan.io/", kind: "Regulated platform", summary: "European embedded banking for accounts, payments and card products through APIs.", regions: ["Europe"], categories: ["sponsor", "accounts", "rails", "cards"], capabilities: ["Accounts", "Payments", "Cards"]},
  {id: "openpayd", name: "OpenPayd", url: "https://www.openpayd.com/", kind: "Regulated platform", summary: "Virtual accounts, payment rails and FX infrastructure for embedded financial products.", regions: ["UK", "Europe", "Global"], categories: ["sponsor", "accounts", "rails", "fx"], capabilities: ["Virtual accounts", "Payments", "FX"]},
  {id: "unit", name: "Unit", url: "https://www.unit.co/", kind: "Banking platform", summary: "US banking-as-a-service platform connecting accounts, cards, payments and compliance workflows.", regions: ["US"], categories: ["sponsor", "accounts", "rails", "cards"], capabilities: ["Accounts", "Cards", "Payments"]},
  {id: "treasury-prime", name: "Treasury Prime", url: "https://www.treasuryprime.com/", kind: "Banking platform", summary: "Embedded banking APIs connecting fintech products with partner banks and payment rails.", regions: ["US"], categories: ["sponsor", "accounts", "rails"], capabilities: ["Bank network", "Accounts", "Payments"]},
  {id: "synctera", name: "Synctera", url: "https://synctera.com/", kind: "Banking platform", summary: "US banking infrastructure for accounts, payments, cards, ledgers and compliance operations.", regions: ["US"], categories: ["sponsor", "accounts", "rails", "cards", "compliance"], capabilities: ["Accounts", "Cards", "Compliance"]},
];
