import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "increase", name: "Increase", url: "https://increase.com/", kind: "Banking platform", summary: "Developer-first APIs for accounts, ACH, wires, cards and realtime payments through bank partners.", regions: ["US"], categories: ["sponsor", "accounts", "rails", "cards"], capabilities: ["Accounts", "Payments", "Cards"]},
  {id: "sumsub", name: "Sumsub", url: "https://sumsub.com/", kind: "Identity & risk", summary: "KYC, KYB, AML, transaction monitoring, fraud prevention and Travel Rule infrastructure.", regions: ["Global"], categories: ["compliance"], capabilities: ["KYC & KYB", "AML", "Fraud"], featured: true},
  {id: "persona", name: "Persona", url: "https://withpersona.com/", kind: "Identity & risk", summary: "Composable identity verification and orchestration for individuals, businesses and reusable workflows.", regions: ["Global"], categories: ["compliance"], capabilities: ["Identity verification", "KYB", "Orchestration"]},
  {id: "alloy", name: "Alloy", url: "https://www.alloy.com/", kind: "Identity & risk", summary: "Identity and fraud decisioning infrastructure for onboarding and ongoing account risk.", regions: ["US", "Global"], categories: ["compliance"], capabilities: ["Decisioning", "KYC", "Fraud"]},
  {id: "trulioo", name: "Trulioo", url: "https://www.trulioo.com/", kind: "Identity & risk", summary: "Global person and business verification with identity data and workflow orchestration.", regions: ["Global"], categories: ["compliance"], capabilities: ["KYC", "KYB", "Identity data"]},
  {id: "veriff", name: "Veriff", url: "https://www.veriff.com/", kind: "Identity & risk", summary: "Identity verification, liveness and fraud controls for digital onboarding.", regions: ["Global"], categories: ["compliance"], capabilities: ["Document verification", "Liveness", "Fraud"]},
  {id: "complyadvantage", name: "ComplyAdvantage", url: "https://complyadvantage.com/", kind: "Financial crime", summary: "AML, sanctions, adverse-media and transaction-monitoring infrastructure.", regions: ["Global"], categories: ["compliance"], capabilities: ["AML", "Sanctions", "Monitoring"]},
  {id: "socure", name: "Socure", url: "https://www.socure.com/", kind: "Identity & risk", summary: "Digital identity, fraud and risk decisioning focused on financial-services onboarding.", regions: ["US"], categories: ["compliance"], capabilities: ["Identity", "Fraud", "Decisioning"]},
  {id: "sardine", name: "Sardine", url: "https://www.sardine.ai/", kind: "Financial crime", summary: "Fraud, AML, payments risk and device intelligence for fintech and digital-asset products.", regions: ["Global"], categories: ["compliance"], capabilities: ["Fraud", "AML", "Device risk"]},
  {id: "unit21", name: "Unit21", url: "https://www.unit21.ai/", kind: "Financial crime", summary: "Fraud and AML monitoring, investigations and case management for financial institutions.", regions: ["Global"], categories: ["compliance", "operations"], capabilities: ["Transaction monitoring", "Cases", "Fraud"]},
  {id: "chainalysis", name: "Chainalysis", url: "https://www.chainalysis.com/", kind: "Blockchain intelligence", summary: "Wallet screening, transaction monitoring and investigations for digital-asset activity.", regions: ["Global"], categories: ["compliance", "stablecoins"], capabilities: ["Wallet screening", "KYT", "Investigations"]},
  {id: "trm-labs", name: "TRM Labs", url: "https://www.trmlabs.com/", kind: "Blockchain intelligence", summary: "Digital-asset risk intelligence, wallet screening and transaction monitoring.", regions: ["Global"], categories: ["compliance", "stablecoins"], capabilities: ["Wallet screening", "KYT", "Risk intelligence"]},
];
