import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "seon", name: "SEON", url: "https://seon.io/", kind: "Fraud platform", summary: "Device, identity, behavioural and payment-fraud signals for realtime risk decisions.", regions: ["Global"], categories: ["compliance"], capabilities: ["Device intelligence", "Fraud signals", "Account protection"]},
  {id: "nium", name: "Nium", url: "https://www.nium.com/", kind: "Regulated payments", summary: "Global accounts, payouts, card issuing and cross-border money movement through one platform.", regions: ["Global"], categories: ["accounts", "rails", "cards", "fx", "stablecoins"], capabilities: ["Accounts", "Payouts", "Cards"], featured: true},
  {id: "airwallex", name: "Airwallex", url: "https://www.airwallex.com/", kind: "Regulated payments", summary: "Multi-currency accounts, collections, payouts and embedded-finance infrastructure.", regions: ["Global"], categories: ["accounts", "rails", "fx"], capabilities: ["Global accounts", "Collections", "Payouts"]},
  {id: "wise-platform", name: "Wise Platform", url: "https://wise.com/platform/", kind: "Regulated payments", summary: "Cross-border accounts, payouts and FX infrastructure embedded into third-party products.", regions: ["Global"], categories: ["accounts", "rails", "fx"], capabilities: ["Cross-border payments", "Accounts", "FX"], featured: true},
  {id: "currencycloud", name: "Currencycloud", url: "https://www.currencycloud.com/", kind: "Regulated payments", summary: "Multi-currency accounts, collections, payouts and FX APIs for fintech products.", regions: ["Global"], categories: ["accounts", "rails", "fx"], capabilities: ["Virtual accounts", "Payments", "FX"]},
  {id: "modulr", name: "Modulr", url: "https://www.modulrfinance.com/", kind: "Regulated payments", summary: "Account and payment infrastructure for UK and European embedded finance.", regions: ["UK", "Europe"], categories: ["accounts", "rails"], capabilities: ["Accounts", "Payments", "Embedded finance"]},
  {id: "thunes", name: "Thunes", url: "https://www.thunes.com/", kind: "Payments network", summary: "Cross-border payment and payout network connecting banks, wallets and local payment methods.", regions: ["Global"], categories: ["rails"], capabilities: ["Payout network", "Wallets", "Cross-border"]},
  {id: "terrapay", name: "TerraPay", url: "https://www.terrapay.com/", kind: "Payments network", summary: "Global money-movement infrastructure across bank accounts, wallets and payment networks.", regions: ["Global"], categories: ["rails"], capabilities: ["Cross-border payouts", "Wallets", "Bank transfers"]},
  {id: "dlocal", name: "dLocal", url: "https://www.dlocal.com/", kind: "Payments network", summary: "Local pay-ins and payouts across emerging markets through one integration.", regions: ["LATAM", "Africa", "APAC", "Global"], categories: ["rails"], capabilities: ["Local payments", "Payouts", "Emerging markets"]},
  {id: "rapyd", name: "Rapyd", url: "https://www.rapyd.net/", kind: "Fintech platform", summary: "Collections, payouts, wallets, cards and local payment methods through a global API platform.", regions: ["Global"], categories: ["accounts", "rails", "cards"], capabilities: ["Collections", "Payouts", "Wallets"]},
  {id: "noah", name: "Noah", url: "https://noah.com/", kind: "Stablecoin payments", summary: "Virtual accounts, stablecoin conversion, pay-ins, payouts and cross-border settlement infrastructure.", regions: ["Global"], categories: ["accounts", "rails", "stablecoins", "fx"], capabilities: ["Virtual accounts", "Stablecoin rails", "Payouts"], featured: true},
  {id: "peer", name: "Peer", url: "https://peer.xyz/", kind: "Stablecoin payments", summary: "Fiat and stablecoin movement infrastructure for global accounts, conversion and payouts.", regions: ["Global"], categories: ["rails", "stablecoins", "fx"], capabilities: ["Fiat rails", "Stablecoins", "Cross-border"], featured: true},
];
