import type { Provider } from "./types";

export const PROVIDERS: Provider[] = [
  {id: "lithic", name: "Lithic", url: "https://www.lithic.com/", kind: "Card issuing", summary: "Developer-first card issuing, processing and programme controls.", regions: ["US"], categories: ["cards"], capabilities: ["Issuing", "Processing", "Controls"]},
  {id: "marqeta", name: "Marqeta", url: "https://www.marqeta.com/", kind: "Card issuing", summary: "Modern card issuing and processing infrastructure for configurable payment programmes.", regions: ["Global"], categories: ["cards"], capabilities: ["Issuing", "Processing", "Authorisations"]},
  {id: "stripe-issuing", name: "Stripe Issuing", url: "https://stripe.com/issuing", kind: "Card issuing", summary: "Virtual and physical card issuing integrated with Stripe's payments infrastructure.", regions: ["Multi-region"], categories: ["cards"], capabilities: ["Issuing", "Cards", "Payments"]},
  {id: "adyen-issuing", name: "Adyen Issuing", url: "https://www.adyen.com/issuing", kind: "Card issuing", summary: "Card issuing, processing and payment infrastructure within Adyen's global platform.", regions: ["Global"], categories: ["cards", "rails"], capabilities: ["Issuing", "Processing", "Payments"]},
  {id: "highnote", name: "Highnote", url: "https://highnote.com/", kind: "Card issuing", summary: "Embedded card and payment products with configurable ledgers, controls and workflows.", regions: ["US"], categories: ["cards"], capabilities: ["Issuing", "Ledger", "Controls"]},
  {id: "enfuce", name: "Enfuce", url: "https://enfuce.com/", kind: "Card issuing", summary: "European card issuing, processing and compliance infrastructure.", regions: ["Europe"], categories: ["cards"], capabilities: ["Issuing", "Processing", "Compliance"]},
  {id: "galileo", name: "Galileo", url: "https://www.galileo-ft.com/", kind: "Card and account platform", summary: "Processing infrastructure for cards, accounts, payments and digital financial products.", regions: ["Global"], categories: ["cards", "accounts"], capabilities: ["Processing", "Cards", "Accounts"]},
  {id: "i2c", name: "i2c", url: "https://www.i2cinc.com/", kind: "Card processing", summary: "Global card processing and configurable payment-product infrastructure.", regions: ["Global"], categories: ["cards"], capabilities: ["Processing", "Credit & debit", "Programme controls"]},
  {id: "paymentology", name: "Paymentology", url: "https://www.paymentology.com/", kind: "Card processing", summary: "Cloud-based card issuing and processing infrastructure across multiple markets.", regions: ["Global"], categories: ["cards"], capabilities: ["Issuing", "Processing", "Cloud platform"]},
  {id: "thredd", name: "Thredd", url: "https://www.thredd.com/", kind: "Card processing", summary: "Issuer processing and card-programme infrastructure for fintechs and banks.", regions: ["Global"], categories: ["cards"], capabilities: ["Issuer processing", "Cards", "Programme operations"]},
  {id: "lmax", name: "LMAX Group", url: "https://www.lmax.com/", kind: "Trading venue", summary: "Institutional FX and digital-asset execution venues and market access.", regions: ["Global"], categories: ["fx"], capabilities: ["Institutional FX", "Digital assets", "Execution"]},
  {id: "integral", name: "Integral", url: "https://www.integral.com/", kind: "FX technology", summary: "Cloud-based FX trading, liquidity aggregation, pricing and workflow technology.", regions: ["Global"], categories: ["fx"], capabilities: ["Liquidity aggregation", "Pricing", "Execution"]},
];
