/** Shared kernel for the Blueballs API.
 *
 *  M2 FAN-OUT CONTRACT — read before adding a family:
 *  - Each resource family lives in exactly ONE file: `apps/api/src/routes/<family>.js`
 *  - A family file imports from here and calls `route(...)`. It NEVER edits server.js.
 *  - Anything catalogued in src/endpoints.ts but not registered gets an automatic 501
 *    at boot. Implement a route and its stub disappears — no coordination needed.
 *  - Do not edit this file during fan-out. It is a frozen shared surface.
 */

import { randomBytes } from "node:crypto";
import { ksuid, toMinor, fromMinor, ApiError, db, emit, post, balanceOf, collection } from "./lib.js";

export { ksuid, toMinor, fromMinor, ApiError, db, emit, post, balanceOf, collection, randomBytes };

/* ---------------- reference tables ---------------- */
export const RAILS = {
  sepa_instant: { id: "sepa_instant", currency: "EUR", speed: "seconds", cutoff: null, weekend: true, min: "0.01", max: "100000.00" },
  sepa: { id: "sepa", currency: "EUR", speed: "next business day", cutoff: "15:00 CET", weekend: false, min: "0.01", max: "999999.00" },
  faster_payments: { id: "faster_payments", currency: "GBP", speed: "seconds", cutoff: null, weekend: true, min: "0.01", max: "1000000.00" },
  ach: { id: "ach", currency: "USD", speed: "1-2 business days", cutoff: "17:00 ET", weekend: false, min: "0.01", max: "25000.00" },
  wire: { id: "wire", currency: "USD", speed: "same day", cutoff: "16:00 ET", weekend: false, min: "100.00", max: "1000000.00" },
  paynow: { id: "paynow", currency: "SGD", speed: "seconds", cutoff: null, weekend: true, min: "0.01", max: "200000.00" },
};
export const RATES = { USD: 1, EUR: 1.083, GBP: 1.271, SGD: 0.742, USDC: 1, MYR: 0.213 };
export const THIN = new Set(["MYR"]);

/* ---------------- route registry ---------------- */
export const routes = [];

/**
 * Register a route.
 * @param method  GET | POST | PATCH | PUT | DELETE
 * @param pattern e.g. "/v2/cards/:id/freeze"
 * @param handler ({ params, body, url, key, req }) => result  — throw ApiError for failures
 * @param opts    { public: true } to skip auth. Default is auth required.
 */
export const route = (method, pattern, handler, opts = {}) => {
  const key = `${method} ${pattern}`;
  if (routes.some((r) => `${r.method} ${r.pattern}` === key)) {
    throw new Error(`Duplicate route ${key} — two families are claiming the same path`);
  }
  routes.push({ method, pattern, parts: pattern.split("/").filter(Boolean), handler, public: !!opts.public });
};

export const isRegistered = (method, pattern) =>
  routes.some((r) => r.method === method && r.pattern === pattern);

export const match = (method, path) => {
  const seg = path.split("/").filter(Boolean);
  for (const r of routes) {
    if (r.method !== method || r.parts.length !== seg.length) continue;
    const params = {};
    let ok = true;
    for (let i = 0; i < r.parts.length; i++) {
      const p = r.parts[i];
      if (p.startsWith(":")) params[p.slice(1)] = decodeURIComponent(seg[i]);
      else if (p !== seg[i]) { ok = false; break; }
    }
    if (ok) return { r, params };
  }
  return null;
};

/* ---------------- handler helpers ---------------- */
/** Throw a 400 listing every missing field at once, not one at a time. */
export function need(body, fields) {
  const errors = fields
    .filter((f) => body[f] === undefined || body[f] === "")
    .map((f) => ({ field: f, message: "is required", code: "missing" }));
  if (errors.length) throw new ApiError("validation-error", 400, "Some required fields are missing", errors);
}

/** Fetch or 404 with a readable detail. */
export function must(collection, id, noun) {
  const row = collection.get(id);
  if (!row) throw new ApiError("not-found", 404, `No ${noun} ${id}`);
  return row;
}

/** Cursor pagination — never offset. */
export const paginate = (rows, url) => {
  const limit = Math.min(Number(url.searchParams.get("limit") || 25), 100);
  const after = url.searchParams.get("starting_after");
  let start = 0;
  if (after) {
    const i = rows.findIndex((r) => r.id === after);
    if (i === -1) throw new ApiError("invalid-identifier", 400, `Unknown cursor ${after}`);
    start = i + 1;
  }
  const page = rows.slice(start, start + limit);
  return { object: "list", data: page, has_more: start + limit < rows.length, next_cursor: page.at(-1)?.id ?? null };
};

export const now = () => new Date().toISOString();
