/** Shared kernel for the Blueballs API.
 *
 *  M2 FAN-OUT CONTRACT — read before adding a family:
 *  - Each resource family lives in exactly ONE file: `apps/api/src/routes/<family>.js`
 *  - A family file imports from here and calls `route(...)`. It NEVER edits server.js.
 *  - Anything catalogued in src/endpoints.ts but not registered gets an automatic 501
 *    at boot. Implement a route and its stub disappears — no coordination needed.
 *  - Do not edit this file during fan-out. It is a frozen shared surface.
 */

import { randomBytes } from "node:crypto";
import {
  ksuid,
  toMinor,
  fromMinor,
  ApiError,
  db,
  emit,
  post,
  balanceOf,
  collection,
  subscribeToEvents,
} from "./lib.js";

export {
  ksuid,
  toMinor,
  fromMinor,
  ApiError,
  db,
  emit,
  post,
  balanceOf,
  collection,
  subscribeToEvents,
  randomBytes,
};

/* ---------------- reference tables ---------------- */
export const RAILS = {
  sepa_instant: {
    id: "sepa_instant",
    currency: "EUR",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "100000.00",
  },
  sepa: {
    id: "sepa",
    currency: "EUR",
    speed: "next business day",
    cutoff: "15:00 CET",
    weekend: false,
    min: "0.01",
    max: "999999.00",
  },
  faster_payments: {
    id: "faster_payments",
    currency: "GBP",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "1000000.00",
  },
  ach: {
    id: "ach",
    currency: "USD",
    speed: "1-2 business days",
    cutoff: "17:00 ET",
    weekend: false,
    min: "0.01",
    max: "25000.00",
  },
  wire: {
    id: "wire",
    currency: "USD",
    speed: "same day",
    cutoff: "16:00 ET",
    weekend: false,
    min: "100.00",
    max: "1000000.00",
  },
  paynow: {
    id: "paynow",
    currency: "SGD",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "200000.00",
  },
};
// Fiat, then the stablecoins at their peg. A stablecoin trades at its peg by
// definition, so EURC carries EUR's rate.
//
// The stablecoin entries were missing: assets.js defines USDC and EURC and the
// FX engine prices corridors in them, but this list is what POST /v2/accounts
// validates against. A liquidity provider could not hold the currency they were
// being asked to commit. Keep in sync with STABLECOINS in assets.js.
export const RATES = {
  USD: 1,
  EUR: 1.083,
  GBP: 1.271,
  SGD: 0.742,
  MYR: 0.213,
  USDC: 1,
  EURC: 1.083,
};
export const THIN = new Set(["MYR"]);

/* ---------------- route registry ---------------- */
export const routes = [];

/**
 * Register a route.
 * @param method  GET | POST | PATCH | PUT | DELETE
 * @param pattern e.g. "/v2/cards/:id/freeze"
 * @param handler ({ params, body, url, key, req }) => result  — throw ApiError for failures
 * @param opts    { access: PUBLIC | TENANT | OPERATOR | GLOBAL_READ, created?: boolean }. Default TENANT/200.
 */
export const route = (method, pattern, handler, opts = {}) => {
  const key = `${method} ${pattern}`;
  if (routes.some((r) => `${r.method} ${r.pattern}` === key)) {
    throw new Error(
      `Duplicate route ${key} — two families are claiming the same path`,
    );
  }
  const access = opts.access ?? (opts.public ? "PUBLIC" : "TENANT");
  if (!["PUBLIC", "TENANT", "OPERATOR", "GLOBAL_READ"].includes(access)) {
    throw new Error(`Invalid access class ${access} for ${key}`);
  }
  const successStatus = opts.created ? 201 : 200;
  routes.push({
    method,
    pattern,
    parts: pattern.split("/").filter(Boolean),
    handler,
    access,
    successStatus,
  });
};

export const isRegistered = (method, pattern) =>
  routes.some((r) => r.method === method && r.pattern === pattern);

export const match = (method, path) => {
  const seg = path.split("/").filter(Boolean);
  for (const r of routes) {
    if (r.method !== method || r.parts.length !== seg.length) continue;
    const params = {};
    let ok = true;
    for (let i = 0; i < r.parts.length; i++) {
      const p = r.parts[i];
      if (p.startsWith(":")) params[p.slice(1)] = decodeURIComponent(seg[i]);
      else if (p !== seg[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return { r, params };
  }
  return null;
};

/* ---------------- handler helpers ---------------- */
/** Throw a 400 listing every missing field at once, not one at a time. */
export function need(body, fields) {
  const errors = fields
    .filter((f) => body[f] === undefined || body[f] === "")
    .map((f) => ({ field: f, message: "is required", code: "missing" }));
  if (errors.length)
    throw new ApiError(
      "validation-error",
      400,
      "Some required fields are missing",
      errors,
    );
}

/** Parse a decimal-string money input and require an economically meaningful
 * positive amount. Read paths should continue to use toMinor directly. */
export function positiveMinor(value, field = "amount") {
  const minor = toMinor(value);
  if (minor <= 0n) {
    throw new ApiError(
      "validation-error",
      400,
      `${field} must be greater than zero`,
      [{ field, message: "must be greater than zero", code: "not_positive" }],
    );
  }
  return minor;
}

/** Stable authenticated tenant identity. Keys can rotate without changing it. */
export function principalId(key) {
  if (!key?.tenant_id) {
    throw new ApiError(
      "internal-error",
      500,
      "Authenticated key has no tenant principal",
    );
  }
  return key.tenant_id;
}

/** Tenant isolation. A row that carries an `owner` is tenant data and is visible
 *  only to the key that created it. Reference data (rails, corridors, calendars)
 *  has no `owner` and stays readable by everyone.
 *
 *  This answers 404, not 403, on purpose: a 403 would confirm that someone else's
 *  identifier exists, which is itself a disclosure. */
export function ownedBy(row, key, noun, id) {
  if (key && row.owner !== principalId(key)) {
    throw new ApiError("not-found", 404, `No ${noun} ${id ?? row.id}`);
  }
  return row;
}

/** Every row of `rows` this key is allowed to see.
 *
 *  Fails closed. An earlier version exempted rows with no `owner` so that
 *  reference data stayed readable, which left every record created before
 *  ownership existed readable by anyone — the exposure survived the fix that
 *  was supposed to close it. Reference data is served by public routes, where
 *  `key` is undefined, so it does not need the exemption. */
export const visibleTo = (rows, key) =>
  rows.filter((r) => !key || r.owner === principalId(key));

/** Fetch or 404 with a readable detail. Pass `key` to scope it to one tenant. */
export function must(collection, id, noun, key) {
  const row = collection.get(id);
  if (!row) throw new ApiError("not-found", 404, `No ${noun} ${id}`);
  return ownedBy(row, key, noun, id);
}

/** Cursor pagination — never offset. */
export const paginate = (rows, url) => {
  const requestedLimit = Number(url.searchParams.get("limit") || 25);
  if (!Number.isInteger(requestedLimit) || requestedLimit < 1) {
    throw new ApiError(
      "validation-error",
      400,
      "limit must be a positive integer",
    );
  }
  const limit = Math.min(requestedLimit, 100);
  const after = url.searchParams.get("starting_after");
  const before = url.searchParams.get("ending_before");
  if (after && before) {
    throw new ApiError(
      "validation-error",
      400,
      "Use starting_after or ending_before, not both",
    );
  }
  if (before) {
    const end = rows.findIndex((r) => r.id === before);
    if (end === -1)
      throw new ApiError("invalid-identifier", 400, `Unknown cursor ${before}`);
    const start = Math.max(0, end - limit);
    const page = rows.slice(start, end);
    return {
      object: "list",
      data: page,
      has_more: start > 0,
      next_cursor: page.at(0)?.id ?? null,
    };
  }
  let start = 0;
  if (after) {
    const i = rows.findIndex((r) => r.id === after);
    if (i === -1)
      throw new ApiError("invalid-identifier", 400, `Unknown cursor ${after}`);
    start = i + 1;
  }
  const page = rows.slice(start, start + limit);
  return {
    object: "list",
    data: page,
    has_more: start + limit < rows.length,
    next_cursor: page.at(-1)?.id ?? null,
  };
};

export const now = () => new Date().toISOString();
