/** Shared kernel for the Blueballs API.
 *
 *  M2 FAN-OUT CONTRACT — read before adding a family:
 *  - Each resource family lives in exactly ONE file: `apps/api/src/routes/<family>.js`
 *  - A family file imports from here and calls `route(...)`. It NEVER edits server.js.
 *  - Anything catalogued in src/endpoints.ts but not registered gets an automatic 501
 *    at boot. Implement a route and its stub disappears — no coordination needed.
 *  - Do not edit this file during fan-out. It is a frozen shared surface.
 */

import { createHash, randomBytes } from "node:crypto";
import {
  ksuid,
  toMinor,
  fromMinor,
  ApiError,
  db,
  emit,
  post,
  balanceOf,
  collection as persistentCollection,
  inRequestScope,
  currentCommandId,
  setCommandContext,
  subscribeToEvents,
  subscribeToEventsBeforeCommit,
} from "./lib.js";
import {
  BANKING_COLLECTION_TABLE_SET,
  migrateBankingSchema,
} from "./schema.js";
import {
  publicResponse,
  validateSuccessfulResponse,
} from "./response-validation.js";
import {
  assertKeyPermission,
  childPermissions,
  publicKeyPermissions,
} from "./key-permissions.js";

migrateBankingSchema();

export function collection(name) {
  if (!BANKING_COLLECTION_TABLE_SET.has(name)) {
    throw new Error(
      `Durable collection ${name} is not registered in the banking schema`,
    );
  }
  if (name === "auditRecords") {
    throw new Error(
      "auditRecords is append-only and may only be written by the banking command boundary",
    );
  }
  return persistentCollection(name);
}

export {
  ksuid,
  toMinor,
  fromMinor,
  ApiError,
  db,
  emit,
  post,
  balanceOf,
  inRequestScope,
  currentCommandId,
  setCommandContext,
  subscribeToEvents,
  subscribeToEventsBeforeCommit,
  randomBytes,
};

/* ---------------- reference tables ---------------- */
export const RAILS = {
  sepa_instant: {
    id: "sepa_instant",
    currency: "EUR",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "100000.00",
  },
  sepa: {
    id: "sepa",
    currency: "EUR",
    speed: "next business day",
    cutoff: "15:00 CET",
    weekend: false,
    min: "0.01",
    max: "999999.00",
  },
  faster_payments: {
    id: "faster_payments",
    currency: "GBP",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "1000000.00",
  },
  ach: {
    id: "ach",
    currency: "USD",
    speed: "1-2 business days",
    cutoff: "17:00 ET",
    weekend: false,
    min: "0.01",
    max: "25000.00",
  },
  wire: {
    id: "wire",
    currency: "USD",
    speed: "same day",
    cutoff: "16:00 ET",
    weekend: false,
    min: "100.00",
    max: "1000000.00",
  },
  paynow: {
    id: "paynow",
    currency: "SGD",
    speed: "seconds",
    cutoff: null,
    weekend: true,
    min: "0.01",
    max: "200000.00",
  },
};

export const RATES = {
  USD: 1,
  EUR: 1.083,
  GBP: 1.271,
  SGD: 0.742,
  MYR: 0.213,
  USDC: 1,
  EURC: 1.083,
};
export const THIN = new Set(["MYR"]);

/* ---------------- route registry ---------------- */
export const routes = [];
const RESPONSE_CONTRACT_VALIDATION =
  process.env.RESPONSE_CONTRACT_VALIDATION === "true";

function auditSourceHash(req) {
  const source =
    req?.headers?.["cf-connecting-ip"] ?? req?.socket?.remoteAddress ?? null;
  return source
    ? createHash("sha256").update(String(source)).digest("hex")
    : null;
}

function persistedKeyById(id, tenantId) {
  return [...db.keys.values()].find(
    (candidate) =>
      candidate.id === id && (!tenantId || candidate.tenant_id === tenantId),
  );
}

/**
 * Register a route.
 * Public serialization, command audit metadata and tenant-key authorization are
 * centralized here so 181 handlers cannot drift into different security rules.
 */
export const route = (method, pattern, handler, opts = {}) => {
  const key = `${method} ${pattern}`;
  if (routes.some((r) => `${r.method} ${r.pattern}` === key)) {
    throw new Error(
      `Duplicate route ${key} — two families are claiming the same path`,
    );
  }
  const access = opts.access ?? (opts.public ? "PUBLIC" : "TENANT");
  if (!["PUBLIC", "TENANT", "OPERATOR", "GLOBAL_READ"].includes(access)) {
    throw new Error(`Invalid access class ${access} for ${key}`);
  }
  const successStatus = opts.created ? 201 : 200;

  const publicHandler = async (ctx) => {
    if (currentCommandId()) {
      setCommandContext({
        operation: key,
        method,
        path: ctx.url?.pathname ?? pattern,
        access,
        tenant_id: ctx.key?.tenant_id ?? null,
        actor_id: ctx.key?.id ?? null,
        actor_scope: ctx.key?.scope ?? (access === "PUBLIC" ? "public" : null),
        source_hash: auditSourceHash(ctx.req),
        audit: access !== "PUBLIC" || method !== "GET",
      });
    }

    if (ctx.key && access !== "PUBLIC" && access !== "OPERATOR") {
      assertKeyPermission(ctx.key, method, pattern);
    }

    // Validate child permissions before the route creates a credential so an
    // escalation attempt leaves no key row behind.
    const requestedChildPermissions =
      method === "POST" && pattern === "/v2/keys" && ctx.key
        ? childPermissions(ctx.key, ctx.body?.permissions)
        : null;

    let result = await handler(ctx);

    if (method === "POST" && pattern === "/v2/auth/signup" && result?.id) {
      const stored = persistedKeyById(result.id, result.tenant_id);
      if (stored) stored.permissions = ["*"];
      result = { ...result, permissions: ["*"] };
    }

    if (
      method === "POST" &&
      pattern === "/v2/keys" &&
      result?.id &&
      requestedChildPermissions
    ) {
      const stored = persistedKeyById(result.id, ctx.key?.tenant_id);
      if (stored) stored.permissions = requestedChildPermissions;
      result = { ...result, permissions: requestedChildPermissions };
    }

    if (method === "GET" && pattern === "/v2/keys" && ctx.key) {
      result = {
        ...result,
        current: {
          key_id: ctx.key.id,
          tenant_id: ctx.key.tenant_id,
          scope: ctx.key.scope,
          permissions: publicKeyPermissions(ctx.key),
        },
        data: Array.isArray(result?.data)
          ? result.data.map((candidate) => ({
              ...candidate,
              permissions: publicKeyPermissions(candidate),
            }))
          : [],
      };
    }

    if (method === "GET" && pattern === "/v2/keys/:id" && result?.id) {
      result = { ...result, permissions: publicKeyPermissions(result) };
    }

    // Public signup has no authenticated actor at entry. Once the key exists,
    // attach the newly-created principal to the same atomic audit record.
    if (
      currentCommandId() &&
      access === "PUBLIC" &&
      method !== "GET" &&
      result?.tenant_id
    ) {
      setCommandContext({
        tenant_id: result.tenant_id,
        actor_id: result.id ?? null,
        actor_scope: result.scope ?? "public",
      });
    }

    return RESPONSE_CONTRACT_VALIDATION
      ? validateSuccessfulResponse(method, pattern, result)
      : publicResponse(result);
  };

  routes.push({
    method,
    pattern,
    parts: pattern.split("/").filter(Boolean),
    handler: publicHandler,
    access,
    successStatus,
  });
};

export const isRegistered = (method, pattern) =>
  routes.some((r) => r.method === method && r.pattern === pattern);

export const match = (method, path) => {
  const seg = path.split("/").filter(Boolean);
  for (const r of routes) {
    if (r.method !== method || r.parts.length !== seg.length) continue;
    const params = {};
    let ok = true;
    for (let i = 0; i < r.parts.length; i++) {
      const p = r.parts[i];
      if (p.startsWith(":")) params[p.slice(1)] = decodeURIComponent(seg[i]);
      else if (p !== seg[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return { r, params };
  }
  return null;
};

/* ---------------- handler helpers ---------------- */
export function need(body, fields) {
  const errors = fields
    .filter((f) => body[f] === undefined || body[f] === "")
    .map((f) => ({ field: f, message: "is required", code: "missing" }));
  if (errors.length)
    throw new ApiError(
      "validation-error",
      400,
      "Some required fields are missing",
      errors,
    );
}

export function positiveMinor(value, field = "amount") {
  const minor = toMinor(value);
  if (minor <= 0n) {
    throw new ApiError(
      "validation-error",
      400,
      `${field} must be greater than zero`,
      [{ field, message: "must be greater than zero", code: "not_positive" }],
    );
  }
  return minor;
}

export function principalId(key) {
  if (!key?.tenant_id) {
    throw new ApiError(
      "internal-error",
      500,
      "Authenticated key has no tenant principal",
    );
  }
  return key.tenant_id;
}

export function ownedBy(row, key, noun, id) {
  if (key && row.owner !== principalId(key)) {
    throw new ApiError("not-found", 404, `No ${noun} ${id ?? row.id}`);
  }
  return row;
}

export const visibleTo = (rows, key) =>
  rows.filter((r) => !key || r.owner === principalId(key));

export function must(collection, id, noun, key) {
  const row = collection.get(id);
  if (!row) throw new ApiError("not-found", 404, `No ${noun} ${id}`);
  return ownedBy(row, key, noun, id);
}

export const paginate = (rows, url) => {
  const requestedLimit = Number(url.searchParams.get("limit") || 25);
  if (!Number.isInteger(requestedLimit) || requestedLimit < 1) {
    throw new ApiError(
      "validation-error",
      400,
      "limit must be a positive integer",
    );
  }
  if (requestedLimit > 100) {
    throw new ApiError(
      "validation-error",
      400,
      "limit must be no greater than 100",
    );
  }
  const limit = requestedLimit;
  const after = url.searchParams.get("starting_after");
  const before = url.searchParams.get("ending_before");
  if (after && before) {
    throw new ApiError(
      "validation-error",
      400,
      "Use starting_after or ending_before, not both",
    );
  }
  if (before) {
    const end = rows.findIndex((r) => r.id === before);
    if (end === -1)
      throw new ApiError("invalid-identifier", 400, `Unknown cursor ${before}`);
    const start = Math.max(0, end - limit);
    const page = rows.slice(start, end);
    return {
      object: "list",
      data: page,
      has_more: start > 0,
      next_cursor: page.at(0)?.id ?? null,
    };
  }
  let start = 0;
  if (after) {
    const i = rows.findIndex((r) => r.id === after);
    if (i === -1)
      throw new ApiError("invalid-identifier", 400, `Unknown cursor ${after}`);
    start = i + 1;
  }
  const page = rows.slice(start, start + limit);
  return {
    object: "list",
    data: page,
    has_more: start + limit < rows.length,
    next_cursor: page.at(-1)?.id ?? null,
  };
};

export const now = () => new Date().toISOString();
