#!/usr/bin/env node
/**
 * Validate and embed apps/fx-node/openapi.yaml for Node and Cloudflare Workers.
 *
 * The checked-in YAML is the public source contract. This generator refuses to
 * publish it when authoritative finality/evidence operations lose their distinct
 * operator credential or when health/source-parity metadata drifts.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(
  new URL("../apps/fx-node/openapi.yaml", import.meta.url),
);
const out = fileURLToPath(
  new URL("../apps/fx-node/src/openapi.generated.js", import.meta.url),
);

const yaml = readFileSync(src, "utf8");

const operatorPaths = [
  "/v2/fx/fiat/attestations",
  "/v2/fx/fiat/intents/{intentId}/settle",
  "/v2/fx/ops/quotes/{quoteId}/confirmed",
  "/v2/fx/ops/quotes/{quoteId}/failed",
];

function pathBlock(path) {
  const marker = `  ${path}:\n`;
  const start = yaml.indexOf(marker);
  if (start < 0) throw new Error(`FX OpenAPI is missing ${path}`);
  const nextPath = yaml.indexOf("\n  /", start + marker.length);
  const components = yaml.indexOf("\ncomponents:", start + marker.length);
  const candidates = [nextPath, components].filter((value) => value >= 0);
  const end = candidates.length ? Math.min(...candidates) : yaml.length;
  return yaml.slice(start, end);
}

if (!yaml.includes("  - clientBearerAuth: []")) {
  throw new Error("FX OpenAPI must default authenticated client operations to clientBearerAuth");
}
if (!yaml.includes("    operatorBearerAuth:\n      type: http\n      scheme: bearer")) {
  throw new Error("FX OpenAPI must declare operatorBearerAuth");
}
for (const path of operatorPaths) {
  const block = pathBlock(path);
  if (!/security:\n\s+- operatorBearerAuth: \[\]/.test(block)) {
    throw new Error(`${path} must require operatorBearerAuth`);
  }
}
const health = pathBlock("/health");
if (!health.includes("required: [status, service, source_commit]") || !health.includes("source_commit:")) {
  throw new Error("FX health contract must expose source_commit parity evidence");
}
if (yaml.includes("bearerAuth:")) {
  throw new Error("legacy single-key bearerAuth must not reappear in the FX contract");
}
if (yaml.includes("`") || yaml.includes("${")) {
  throw new Error("FX OpenAPI cannot contain template-literal delimiters in embedded form");
}

const module = `// GENERATED by scripts/build-openapi.mjs from apps/fx-node/openapi.yaml
// Do not edit. Run node scripts/build-openapi.mjs after changing the spec.
export const OPENAPI_YAML = String.raw\`${yaml}\`;
`;

writeFileSync(out, module);
console.log(
  `validated authority boundaries and embedded ${yaml.split("\n").length} lines of FX OpenAPI into ${out.split("/").slice(-4).join("/")}`,
);
