#!/usr/bin/env node
/**
 * Embeds apps/fx-node/openapi.yaml into a JS module.
 *
 * Cloudflare Workers have no filesystem, so the FX node could not readFileSync
 * its own spec there. It shipped a hand-written stub instead — `paths: {}` —
 * and /openapi.fx.yaml served that empty document in production while the real
 * 651-line contract sat in the repository, unreachable by anyone using the API.
 *
 * Generated, committed, and checked for drift by `pnpm verify`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(new URL("../apps/fx-node/openapi.yaml", import.meta.url));
const out = fileURLToPath(new URL("../apps/fx-node/src/openapi.generated.js", import.meta.url));

const yaml = readFileSync(src, "utf8");
const module = `// GENERATED by scripts/build-openapi.mjs from apps/fx-node/openapi.yaml
// Do not edit. Run \`node scripts/build-openapi.mjs\` after changing the spec.
export const OPENAPI_YAML = ${JSON.stringify(yaml)};
`;

writeFileSync(out, module);
console.log(`embedded ${yaml.split("\n").length} lines of OpenAPI into ${out.split("/").slice(-4).join("/")}`);
