import { useState } from "react";
import { Label } from "./Primitives";

function ArrowDefs(){return <defs><marker id="fx-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#6078cb"/></marker><marker id="fx-arrow-soft" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#a9b5da"/></marker><filter id="fx-shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="10" stdDeviation="12" floodColor="#1f315f" floodOpacity=".12"/></filter></defs>}

export function MasterArchitecture(){
  return <section className="fxp-section fx-visual-section"><div className="fxp-section-head"><div><Label>ONE CUSTOMER EXCHANGE</Label><h2>The product stays simple. The infrastructure can be much bigger.</h2><p>A USD → EUR exchange can move through your own market, connected institutions, external venues and fiat edges without changing the customer-facing integration.</p></div></div><div className="fx-canvas fx-master-canvas"><svg viewBox="0 0 1440 760" role="img" aria-label="End-to-end FX infrastructure flow"><ArrowDefs/>
    <path className="fx-route-main" d="M170 380 C270 380 280 380 360 380 S470 380 530 380" markerEnd="url(#fx-arrow)"/>
    <path className="fx-route-main" d="M900 380 C980 380 1010 380 1085 380 S1190 380 1265 380" markerEnd="url(#fx-arrow)"/>
    <path className="fx-route-soft" d="M705 300 C705 240 705 215 705 170" markerEnd="url(#fx-arrow-soft)"/>
    <path className="fx-route-soft" d="M655 455 C590 520 515 555 420 590" markerEnd="url(#fx-arrow-soft)"/>
    <path className="fx-route-soft" d="M755 455 C830 520 905 555 1010 590" markerEnd="url(#fx-arrow-soft)"/>
    <g className="fx-node phone-node" transform="translate(55 270)"><rect width="190" height="220" rx="34"/><text x="95" y="38" textAnchor="middle" className="eyebrow">YOUR PRODUCT</text><text x="95" y="90" textAnchor="middle" className="big">$100,000</text><text x="95" y="122" textAnchor="middle" className="mid">USD → EUR</text><rect x="28" y="160" width="134" height="34" rx="17" className="button"/><text x="95" y="182" textAnchor="middle" className="buttonText">REVIEW EXCHANGE</text></g>
    <g transform="translate(335 310)"><circle cx="70" cy="70" r="67" className="checkpoint"/><text x="70" y="55" textAnchor="middle" className="eyebrow">REQUEST</text><text x="70" y="82" textAnchor="middle" className="nodeTitle">Policy</text><text x="70" y="103" textAnchor="middle" className="tiny">assets · limits · access</text></g>
    <g className="fx-core-node" transform="translate(530 250)" filter="url(#fx-shadow)"><rect width="370" height="260" rx="34"/><text x="185" y="46" textAnchor="middle" className="eyebrow light">YOUR FX STACK</text><text x="185" y="91" textAnchor="middle" className="heroText">Build the route</text><g className="coreItems"><text x="58" y="142">MARKET</text><text x="154" y="142">PRICE</text><text x="245" y="142">RESERVE</text><text x="58" y="188">EXECUTE</text><text x="154" y="188">SETTLE</text><text x="245" y="188">RECONCILE</text></g><text x="185" y="229" textAnchor="middle" className="tiny light">one interface · different market structures</text></g>
    <g transform="translate(585 52)"><circle cx="120" cy="70" r="64" className="sourceHalo"/><text x="120" y="50" textAnchor="middle" className="eyebrow">YOUR MARKET</text><text x="120" y="76" textAnchor="middle" className="nodeTitle">Own flow</text><text x="120" y="98" textAnchor="middle" className="tiny">customers · makers · treasury</text></g>
    <g transform="translate(250 560)"><circle cx="160" cy="55" r="52" className="sourceHalo"/><text x="160" y="44" textAnchor="middle" className="eyebrow">CONNECTED</text><text x="160" y="67" textAnchor="middle" className="nodeTitle">Institutions</text><text x="160" y="88" textAnchor="middle" className="tiny">issuer · bank · LP · JIT</text></g>
    <g transform="translate(875 560)"><circle cx="135" cy="55" r="52" className="sourceHalo"/><text x="135" y="44" textAnchor="middle" className="eyebrow">OPTIONAL</text><text x="135" y="67" textAnchor="middle" className="nodeTitle">External routes</text><text x="135" y="88" textAnchor="middle" className="tiny">venue · aggregator · bridge</text></g>
    <g transform="translate(1070 310)"><circle cx="70" cy="70" r="67" className="checkpoint"/><text x="70" y="55" textAnchor="middle" className="eyebrow">FINALITY</text><text x="70" y="82" textAnchor="middle" className="nodeTitle">Settle</text><text x="70" y="103" textAnchor="middle" className="tiny">token + external evidence</text></g>
    <g className="fx-node result-node" transform="translate(1260 300)"><rect width="130" height="170" rx="26"/><circle cx="65" cy="48" r="22" className="ok"/><path d="M55 48l7 7 14-17" className="check"/><text x="65" y="91" textAnchor="middle" className="eyebrow">CUSTOMER</text><text x="65" y="118" textAnchor="middle" className="nodeTitle">EUR</text><text x="65" y="141" textAnchor="middle" className="tiny">received</text></g>
    <text x="720" y="710" textAnchor="middle" className="caption">THE MARKET, PROVIDERS AND RAILS CAN CHANGE. THE PRODUCT INTEGRATION DOES NOT HAVE TO.</text>
  </svg></div></section>
}

export function OwnMarketGraphic(){
  return <section className="fxp-section fx-visual-section"><div className="fxp-section-head"><div><Label>YOUR MARKET</Label><h2>Run the market behind the exchange.</h2><p>Opposing customer flow, customer and business orders, professional makers, issuers and treasury can all meet inside the same private market.</p></div></div><div className="fx-canvas"><svg viewBox="0 0 1440 780" role="img" aria-label="Private FX market with participant orders and one customer trade"><ArrowDefs/>
    <path className="fx-route-main" d="M720 90L720 205" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M720 540L720 680" markerEnd="url(#fx-arrow)"/>
    <path className="fx-route-soft" d="M235 205 C330 205 350 260 470 292" markerEnd="url(#fx-arrow-soft)"/><path className="fx-route-soft" d="M235 355 C330 355 360 350 470 350" markerEnd="url(#fx-arrow-soft)"/><path className="fx-route-soft" d="M235 505 C335 505 365 430 470 405" markerEnd="url(#fx-arrow-soft)"/>
    <path className="fx-route-soft" d="M1205 205 C1110 205 1090 260 970 292" markerEnd="url(#fx-arrow-soft)"/><path className="fx-route-soft" d="M1205 355 C1110 355 1080 350 970 350" markerEnd="url(#fx-arrow-soft)"/><path className="fx-route-soft" d="M1205 505 C1105 505 1075 430 970 405" markerEnd="url(#fx-arrow-soft)"/>
    <g transform="translate(600 35)"><rect width="240" height="72" rx="36" className="requestPill"/><text x="120" y="29" textAnchor="middle" className="eyebrow light">INCOMING EXCHANGE</text><text x="120" y="53" textAnchor="middle" className="nodeTitle light">$250k USD → EUR</text></g>
    {[[70,160,"CUSTOMER","$40k","limit order"],[70,310,"BUSINESS","$75k","private order"],[70,460,"MARKET MAKER","$300k","resting quote"],[1130,160,"ISSUER","$150k","inventory"],[1130,310,"TREASURY","$90k","risk-limited"],[1130,460,"INSTITUTION","$500k","signed order"]].map(([x,y,k,a,s])=><g key={String(k)} transform={`translate(${x} ${y})`}><circle cx="85" cy="55" r="48" className="participant"/><text x="85" y="44" textAnchor="middle" className="eyebrow">{k}</text><text x="85" y="67" textAnchor="middle" className="nodeTitle">{a}</text><text x="85" y="88" textAnchor="middle" className="tiny">{s}</text></g>)}
    <g className="marketPool" transform="translate(470 205)" filter="url(#fx-shadow)"><path d="M85 0H415c48 0 85 38 85 85v165c0 48-37 85-85 85H85C37 335 0 298 0 250V85C0 38 37 0 85 0Z"/><text x="250" y="50" textAnchor="middle" className="eyebrow light">PRIVATE FX MARKET</text><text x="250" y="88" textAnchor="middle" className="heroText">USDC / EURC</text><line x1="250" y1="115" x2="250" y2="275" className="marketDivider"/><text x="120" y="142" textAnchor="middle" className="eyebrow light">BIDS</text><text x="380" y="142" textAnchor="middle" className="eyebrow light">OFFERS</text><text x="120" y="190" textAnchor="middle" className="marketNumber">$118k</text><text x="380" y="190" textAnchor="middle" className="marketNumber">$265k</text><text x="250" y="235" textAnchor="middle" className="tiny light">price-time matching · partial fills · cancellation</text><rect x="125" y="260" width="250" height="42" rx="21" className="selectedFill"/><text x="250" y="286" textAnchor="middle" className="buttonText">SELECTED INTERNAL FILL · $165k</text></g>
    <g transform="translate(530 665)"><rect width="380" height="70" rx="20" className="darkNote"/><text x="22" y="28" className="eyebrow light">WHAT LEAVES THE MARKET</text><text x="22" y="51" className="nodeTitle light">Aggregate depth, not maker identity</text></g>
  </svg></div></section>
}

export function ProviderParticipation(){
  const [mode,setMode]=useState<"resting"|"inventory"|"jit">("jit");
  const modes={resting:{label:"RESTING ORDERS",caption:"Issuer, bank or LP leaves signed executable orders in the market.",left:"SIGNED ORDERS",mid:"PRIVATE MARKET",right:"SELECTED FILL"},inventory:{label:"AVAILABLE INVENTORY",caption:"A connected institution exposes current price and capacity without joining the public book.",left:"PRICE + CAPACITY",mid:"NORMALISE",right:"EXECUTABLE SLICE"},jit:{label:"JUST-IN-TIME RFQ",caption:"Ask for a short-lived firm price only when incoming flow needs more capacity.",left:"$4m REQUEST",mid:"FAN OUT",right:"FIRM QUOTES"}}[mode];
  return <section className="fxp-section fx-visual-section"><div className="fxp-section-head"><div><Label>CONNECTED FIRMS</Label><h2>They do not all have to provide liquidity the same way.</h2><p>Banks, issuers, LPs and intermediaries can place orders, expose inventory, or answer when flow arrives.</p></div></div><div className="fx-diagram-tabs"><button className={mode==="resting"?"active":""} onClick={()=>setMode("resting")}>Resting orders</button><button className={mode==="inventory"?"active":""} onClick={()=>setMode("inventory")}>Available inventory</button><button className={mode==="jit"?"active":""} onClick={()=>setMode("jit")}>JIT / RFQ</button></div><div className="fx-canvas"><svg viewBox="0 0 1440 660" role="img" aria-label="Institutional participation modes"><ArrowDefs/>
    <text x="720" y="58" textAnchor="middle" className="diagramTitle">{modes.label}</text><text x="720" y="88" textAnchor="middle" className="diagramSub">{modes.caption}</text>
    <path className="fx-route-main" d="M245 315 C360 315 390 315 505 315" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M935 315 C1050 315 1080 315 1195 315" markerEnd="url(#fx-arrow)"/>
    {[[70,170,"ISSUER","mint / redeem + inventory"],[70,310,"BANK","treasury / principal"],[70,450,"MARKET MAKER","professional liquidity"]].map(([x,y,k,s])=><g key={String(k)} transform={`translate(${x} ${y})`}><circle cx="88" cy="55" r="48" className="participant"/><text x="88" y="46" textAnchor="middle" className="eyebrow">{k}</text><text x="88" y="70" textAnchor="middle" className="tiny">{s}</text></g>)}
    <g transform="translate(505 205)" filter="url(#fx-shadow)"><circle cx="215" cy="110" r="108" className="coreCircle"/><text x="215" y="80" textAnchor="middle" className="eyebrow light">{modes.mid}</text><text x="215" y="118" textAnchor="middle" className="heroText">Provider API</text><text x="215" y="150" textAnchor="middle" className="tiny light">quote · capacity · expiry · reserve</text></g>
    <g transform="translate(1120 180)"><path d="M80 0h165c44 0 80 36 80 80v155c0 44-36 80-80 80H80c-44 0-80-36-80-80V80C0 36 36 0 80 0Z" className="quotePanel"/><text x="162" y="42" textAnchor="middle" className="eyebrow">{modes.right}</text>{mode==="jit"?<><text x="38" y="102" className="tiny">Issuer</text><text x="285" y="102" textAnchor="end" className="nodeTitle">$2m · 6s</text><text x="38" y="155" className="tiny">Bank</text><text x="285" y="155" textAnchor="end" className="nodeTitle">$5m · 8s</text><text x="38" y="208" className="tiny">LP</text><text x="285" y="208" textAnchor="end" className="nodeTitle">$3m · 4s</text></>:<><text x="162" y="125" textAnchor="middle" className="heroText dark">{mode==="resting"?"$2.5m":"$5.0m"}</text><text x="162" y="160" textAnchor="middle" className="tiny">price + capacity</text><text x="162" y="205" textAnchor="middle" className="nodeTitle">firm before use</text></>}</g>
    <g transform="translate(510 505)"><rect width="420" height="72" rx="22" className="darkNote"/><text x="210" y="28" textAnchor="middle" className="eyebrow light">SAME ROUTER</text><text x="210" y="52" textAnchor="middle" className="nodeTitle light">Normalise → compare → reserve only what is selected</text></g>
  </svg></div></section>
}

export function FiatEdgeGraphic(){
  const [mode,setMode]=useState<"managed"|"peer"|"issuer">("peer");
  const label=mode==="managed"?"MANAGED PROVIDER":mode==="peer"?"VERIFIED P2P":"DIRECT ISSUER";
  const step=mode==="managed"?"bank / payment instructions → provider confirmation":mode==="peer"?"buyer pays seller → proof verified → escrow releases":"issuer receives fiat → mint / release";
  return <section className="fxp-section fx-visual-section"><div className="fxp-section-head"><div><Label>FIAT AT THE EDGES</Label><h2>You can change the way money gets on-chain without changing the FX market.</h2><p>Managed ramps, direct issuers and verified P2P rails are different ways to create the fiat edge. Stablecoin-to-stablecoin FX skips those edges entirely.</p></div></div><div className="fx-diagram-tabs"><button className={mode==="managed"?"active":""} onClick={()=>setMode("managed")}>Managed provider</button><button className={mode==="peer"?"active":""} onClick={()=>setMode("peer")}>Verified P2P</button><button className={mode==="issuer"?"active":""} onClick={()=>setMode("issuer")}>Direct issuer</button></div><div className="fx-canvas"><svg viewBox="0 0 1440 650" role="img" aria-label="Fiat edge routes into stablecoin FX"><ArrowDefs/>
    <path className="fx-route-main" d="M180 325H390" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M620 325H785" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M985 325H1120" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M1280 325H1370" markerEnd="url(#fx-arrow)"/>
    <g transform="translate(55 245)"><circle cx="80" cy="80" r="74" className="fiatCircle"/><text x="80" y="68" textAnchor="middle" className="heroText dark">BRL</text><text x="80" y="96" textAnchor="middle" className="tiny">customer fiat</text></g>
    <g transform="translate(390 205)" filter="url(#fx-shadow)"><path d="M52 0h180c29 0 52 23 52 52v136c0 29-23 52-52 52H52c-29 0-52-23-52-52V52C0 23 23 0 52 0Z" className="edgePanel"/><text x="142" y="55" textAnchor="middle" className="eyebrow">{label}</text><text x="142" y="92" textAnchor="middle" className="nodeTitle">Fiat → token</text><foreignObject x="30" y="115" width="224" height="92"><div className="svg-wrap">{step}</div></foreignObject></g>
    <g transform="translate(755 245)"><circle cx="80" cy="80" r="74" className="tokenCircle"/><text x="80" y="68" textAnchor="middle" className="heroText light">USDC</text><text x="80" y="96" textAnchor="middle" className="tiny light">stablecoin</text></g>
    <g className="fxCoreRoute" transform="translate(970 205)" filter="url(#fx-shadow)"><rect width="220" height="240" rx="40"/><text x="110" y="55" textAnchor="middle" className="eyebrow light">YOUR FX MARKET</text><text x="110" y="102" textAnchor="middle" className="heroText">USDC</text><path d="M62 126H158" markerEnd="url(#fx-arrow)" className="innerArrow"/><text x="110" y="172" textAnchor="middle" className="heroText">EURC</text><text x="110" y="209" textAnchor="middle" className="tiny light">own market + connected routes</text></g>
    <g transform="translate(1190 245)"><circle cx="80" cy="80" r="74" className="tokenCircle soft"/><text x="80" y="68" textAnchor="middle" className="heroText light">EURC</text><text x="80" y="96" textAnchor="middle" className="tiny light">stablecoin</text></g>
    <g transform="translate(1325 252)"><text x="42" y="48" textAnchor="middle" className="eyebrow">REDEEM</text><text x="42" y="78" textAnchor="middle" className="nodeTitle">EUR</text></g>
    <g transform="translate(415 510)"><rect width="610" height="72" rx="22" className="darkNote"/><text x="305" y="28" textAnchor="middle" className="eyebrow light">NO FIAT EDGE REQUIRED</text><text x="305" y="52" textAnchor="middle" className="nodeTitle light">USDT → EURC can enter the FX market directly</text></g>
  </svg></div></section>
}

const MODELS=[
  {id:"external",title:"External-first",sub:"Launch with ramps, LPs and external routes. Add your own market later.",own:.15,inst:.45,ext:.9},
  {id:"hybrid",title:"Hybrid",sub:"Your market handles natural flow. Institutions and venues extend depth.",own:.65,inst:.65,ext:.45},
  {id:"own",title:"Own-market",sub:"Customer flow, private orders and treasury do most of the work.",own:.95,inst:.35,ext:.2},
  {id:"issuer",title:"Issuer-led",sub:"Issuer inventory and mint/redeem rails sit beside market-maker partners.",own:.45,inst:.9,ext:.25},
] as const;
export function DeploymentBlueprints(){const [idx,setIdx]=useState(1);const m=MODELS[idx];return <section className="fxp-section fx-visual-section"><div className="fxp-section-head"><div><Label>ONE STACK · DIFFERENT BUSINESSES</Label><h2>Choose how much of the market you want to operate.</h2><p>A new fintech can start external-first. A bank can use treasury and JIT relationships. An issuer can centre the market around its own inventory. The underlying interface stays the same.</p></div></div><div className="fx-diagram-tabs">{MODELS.map((x,i)=><button key={x.id} className={i===idx?"active":""} onClick={()=>setIdx(i)}>{x.title}</button>)}</div><div className="fx-canvas"><svg viewBox="0 0 1440 620" role="img" aria-label="Different FX deployment models"><ArrowDefs/>
  <text x="720" y="55" textAnchor="middle" className="diagramTitle">{m.title}</text><text x="720" y="85" textAnchor="middle" className="diagramSub">{m.sub}</text>
  <path className="fx-route-main" d="M230 315H480" markerEnd="url(#fx-arrow)"/><path className="fx-route-main" d="M960 315H1210" markerEnd="url(#fx-arrow)"/>
  <g transform="translate(65 235)"><circle cx="105" cy="80" r="73" className="fiatCircle"/><text x="105" y="66" textAnchor="middle" className="eyebrow">CUSTOMER</text><text x="105" y="96" textAnchor="middle" className="nodeTitle">USD → EUR</text></g>
  <g transform="translate(475 150)" filter="url(#fx-shadow)"><circle cx="245" cy="165" r="160" className="coreCircle"/><text x="245" y="112" textAnchor="middle" className="eyebrow light">YOUR FX STACK</text><text x="245" y="154" textAnchor="middle" className="heroText">Same interface</text><text x="245" y="191" textAnchor="middle" className="tiny light">market · providers · rails · settlement</text><circle cx="130" cy="260" r={52+38*m.own} className="bubble ownBubble"/><circle cx="245" cy="285" r={52+38*m.inst} className="bubble instBubble"/><circle cx="360" cy="260" r={52+38*m.ext} className="bubble extBubble"/><text x="130" y="264" textAnchor="middle" className="bubbleText">OWN</text><text x="245" y="289" textAnchor="middle" className="bubbleText">FIRMS</text><text x="360" y="264" textAnchor="middle" className="bubbleText">EXTERNAL</text></g>
  <g transform="translate(1180 235)"><circle cx="105" cy="80" r="73" className="sourceHalo"/><text x="105" y="66" textAnchor="middle" className="eyebrow">RESULT</text><text x="105" y="96" textAnchor="middle" className="nodeTitle">EUR</text></g>
  <g transform="translate(330 530)"><rect width="780" height="60" rx="20" className="darkNote"/><text x="390" y="37" textAnchor="middle" className="nodeTitle light">Start with what you can access. Internalise more of the economics and execution as you grow.</text></g>
</svg></div></section>}
