import { useMemo, useState } from "react";
import { baselineScenarios, runSimulation } from "../../packages/fx-simulator/src/index.js";
import { Label, Pill } from "./Primitives";
import { SIMULATOR_OPTIONS, SOURCE_LABELS, source, type SimulationResult, type SimulatorKey, type SourceType } from "./model";

export function SimulatorLab() {
  const [scenario, setScenario] = useState<SimulatorKey>("balanced");
  const result = useMemo(() => runSimulation((baselineScenarios() as Record<string, unknown>)[scenario]) as SimulationResult, [scenario]);
  const composition = Object.entries(result.routeComposition).map(([type, value]) => ({ type: type as SourceType, value: Number(value) })).filter((item) => item.value > 0);
  const total = composition.reduce((sum, item) => sum + item.value, 0) || 1;
  return <section className="fxp-section fxp-simulator"><div className="fxp-section-head"><div><Label>DETERMINISTIC SIMULATOR · NOT A LIVE QUOTE</Label><h2>Break the market before your customers do.</h2><p>This runs the same economic simulator used by the FX release gate. It does not alter the reserved trade above.</p></div><a href={source("packages/fx-simulator/src/simulator.js")} target="_blank" rel="noreferrer"><Pill>Open simulator ↗</Pill></a></div><div className="fxp-sim-options">{SIMULATOR_OPTIONS.map((item) => <button type="button" key={item.id} className={scenario === item.id ? "active" : ""} onClick={() => setScenario(item.id)}>{item.label}</button>)}</div><div className="fxp-sim-grid"><div className="fxp-sim-chart"><div className="fxp-bar"><span style={{ width: `${result.fillRatePct}%` }} /></div><div className="fxp-sim-main"><span>Orders filled</span><strong>{result.filledOrders} / {result.requestedOrders}</strong><b>{result.fillRatePct.toFixed(1)}%</b></div><div className="fxp-composition">{composition.map((item) => <div key={item.type} style={{ width: `${(item.value / total) * 100}%` }} title={`${SOURCE_LABELS[item.type]}: ${item.value}`} />)}</div></div><div className="fxp-sim-stats"><div><span>Volume filled</span><strong>{result.volumeFillPct.toFixed(1)}%</strong></div><div><span>No liquidity</span><strong>{result.rejections.NO_LIQUIDITY}</strong></div><div><span>Risk rejections</span><strong>{result.rejections.RISK_LIMIT}</strong></div><div><span>Settlement failures</span><strong>{result.settlementFailures}</strong></div><div><span>Peak principal</span><strong>{result.peakPrincipalExposureAbs}</strong></div><div><span>Hard limit</span><strong>{result.principalHardLimit}</strong></div></div></div></section>;
}
