import { useState } from "react";
import { Label } from "./Primitives";
import { FX_CAPABILITIES, capabilitySource, capabilityTest } from "./capabilities";

const FLOWS = [
  { from:"USD", to:"EUR", pay:"$100,000", receive:"€92,340" },
  { from:"BRL", to:"EUR", pay:"R$500,000", receive:"€84,760" },
  { from:"USDT", to:"EURC", pay:"100,000 USDT", receive:"92,410 EURC" },
] as const;

const statusLabel = (status: string) => status.replace(/_/g, " ");

export function ProductPhone(){
  const [index,setIndex]=useState(0); const flow=FLOWS[index]; const [stage,setStage]=useState<"quote"|"review"|"done">("quote");
  return <div className="fx-phone"><div className="fx-phone-inner"><div className="fx-phone-status"><span>9:41</span><span>▮▮▮ ᯤ ▰</span></div>{stage==="quote"?<><div className="fx-phone-title"><div><small>EXCHANGE</small><h3>{flow.from} → {flow.to}</h3></div><span>PRODUCT EXAMPLE</span></div><div className="fx-phone-box"><small>You pay</small><strong>{flow.pay}</strong><b>{flow.from}</b></div><div className="fx-phone-arrow">↓</div><div className="fx-phone-box"><small>You receive</small><strong>{flow.receive}</strong><b>{flow.to}</b></div><div className="fx-phone-meta"><span>Quote ready</span><b>Review before exchange</b></div><button type="button" onClick={()=>setStage("review")}>Review exchange</button><div className="fx-phone-pairs">{FLOWS.map((item,i)=><button type="button" key={`${item.from}-${item.to}`} className={i===index?"active":""} onClick={()=>{setIndex(i);setStage("quote")}}>{item.from} → {item.to}</button>)}</div><p>Illustrative product interface. Live commercial providers are not implied.</p></>:stage==="review"?<><button className="fx-phone-back" type="button" onClick={()=>setStage("quote")}>← Back</button><div className="fx-phone-review"><small>YOU RECEIVE</small><strong>{flow.receive}</strong></div><div className="fx-phone-lines"><div><span>You pay</span><b>{flow.pay}</b></div><div><span>Pair</span><b>{flow.from} / {flow.to}</b></div><div><span>Route</span><b>Ready</b></div></div><button type="button" onClick={()=>setStage("done")}>Confirm example</button><p>No money moves in this product example.</p></>:<div className="fx-phone-done"><i>✓</i><Label>EXAMPLE COMPLETE</Label><h3>Exchange confirmed</h3><p>The customer sees one exchange. The infrastructure underneath can be assembled very differently.</p><button type="button" onClick={()=>setStage("quote")}>Start again</button></div>}</div></div>
}

export function OwnershipStory(){
  const [level,setLevel]=useState<0|1|2>(0);
  const copy=[
    {k:"USE",t:"Start with what already exists.",p:"Connect the providers you need to launch. Keep the customer experience and FX interface in your product."},
    {k:"ORCHESTRATE",t:"Add your own rules and counterparties.",p:"Combine your market with issuers, market makers, banks and external routes instead of depending on one provider."},
    {k:"OPERATE",t:"Own more of the FX business as you grow.",p:"Use customer flow, private orders, treasury and connected institutions inside the same FX stack."},
  ][level];
  return <section className="fxp-section fx-ownership"><div className="fxp-section-head"><div><Label>START SIMPLE. OWN MORE OVER TIME.</Label><h2>You should not have to rebuild FX when your business grows.</h2><p>Launch with external infrastructure. Add your own market and institutional relationships later. The customer-facing integration can stay the same.</p></div></div><div className="fx-level-tabs">{(["USE","ORCHESTRATE","OPERATE"] as const).map((item,i)=><button type="button" key={item} className={i===level?"active":""} onClick={()=>setLevel(i as 0|1|2)}><span>0{i+1}</span><b>{item}</b></button>)}</div><div className="fx-level-stage"><div className="fx-level-copy"><Label>{copy.k}</Label><h3>{copy.t}</h3><p>{copy.p}</p></div><OwnershipGraph level={level}/></div></section>
}

function OwnershipGraph({level}:{level:0|1|2}){
  return <div className={`fx-own-graph level-${level}`}><div className="fx-own-request"><span>CUSTOMER</span><b>USD → EUR</b></div><i>→</i><div className="fx-own-stack"><span>YOUR FX STACK</span><b>one interface</b></div><i>→</i><div className="fx-own-sources"><div className="external"><span>EXTERNAL</span><b>Provider</b></div>{level>=1&&<><div><span>CONNECTED</span><b>Issuer / LP / bank</b></div><div><span>ROUTE</span><b>External venue</b></div></>}{level>=2&&<><div className="own"><span>YOUR MARKET</span><b>Customer + business orders</b></div><div className="own"><span>YOUR BALANCE SHEET</span><b>Treasury / principal</b></div></>}</div></div>
}

export function OneExchangeFlow(){
  return <section className="fxp-section fx-master"><div className="fxp-section-head"><div><Label>ONE EXCHANGE</Label><h2>The customer sees a quote. The stack sees a route.</h2><p>Policy, market depth, connected firms, fiat edges and settlement can all sit behind the same customer action.</p></div></div><div className="fx-master-line"><div><span>01</span><b>Request</b><small>$100k USD → EUR</small></div><i>→</i><div><span>02</span><b>Check</b><small>policy + supported assets</small></div><i>→</i><div><span>03</span><b>Build route</b><small>own market + connected paths</small></div><i>→</i><div><span>04</span><b>Reserve</b><small>hold selected capacity</small></div><i>→</i><div><span>05</span><b>Execute</b><small>submit each leg</small></div><i>→</i><div><span>06</span><b>Reconcile</b><small>know what actually settled</small></div></div></section>
}

export function PrivateMarket(){
  return <section className="fxp-section fx-private"><div className="fx-private-copy"><Label>YOUR MARKET</Label><h2>Your own market can sit behind the exchange.</h2><p>Customer flow, businesses, professional makers, issuers and treasury can place orders into the same private market. Aggregate depth can be exposed without publishing individual maker identities.</p><div className="fx-private-tags"><span>signed orders</span><span>price-time matching</span><span>partial fills</span><span>reservations</span><span>cancellation</span></div></div><div className="fx-book"><div className="fx-book-head"><b>USDC / EURC</b><span>PRIVATE MARKET</span></div><div className="fx-book-grid"><div><small>SELL EURC</small><p><span>Customer</span><b>25k</b><em>0.9239</em></p><p><span>Business</span><b>80k</b><em>0.9241</em></p><p><span>Market maker</span><b>250k</b><em>0.9243</em></p><p><span>Issuer</span><b>500k</b><em>0.9245</em></p></div><div><small>BUY EURC</small><p><span>Customer</span><b>18k</b><em>0.9235</em></p><p><span>Treasury</span><b>150k</b><em>0.9232</em></p><p><span>Market maker</span><b>300k</b><em>0.9230</em></p><p><span>Business</span><b>90k</b><em>0.9228</em></p></div></div><div className="fx-book-order"><span>PLACE AN ORDER</span><b>USDC / EURC · 50,000 · limit 0.9238</b><button type="button" disabled>API-backed UI comes from canonical order endpoints</button></div></div></section>
}

export function ProviderModes(){
  const [mode,setMode]=useState<"orders"|"inventory"|"jit">("jit");
  const data={orders:{title:"Place orders",body:"A market maker, issuer or institution can leave signed orders in the private market and manage them over time."},inventory:{title:"Expose inventory",body:"A connected institution can expose current executable capacity without becoming a public order-book participant."},jit:{title:"Answer when flow arrives",body:"Ask an approved institution for a short-lived firm price only when the customer request needs it."}}[mode];
  return <section className="fxp-section fx-provider-modes"><div className="fxp-section-head"><div><Label>CONNECTED FIRMS</Label><h2>Providers can connect on their terms.</h2><p>A bank, issuer or market maker does not have to interact with the stack in only one way.</p></div></div><div className="fx-provider-tabs">{(["orders","inventory","jit"] as const).map((item)=><button key={item} type="button" onClick={()=>setMode(item)} className={mode===item?"active":""}>{item==="jit"?"JIT quote":item}</button>)}</div><div className="fx-provider-stage"><div><Label>{mode.toUpperCase()}</Label><h3>{data.title}</h3><p>{data.body}</p></div><div className="fx-rfq"><div className="request"><span>REQUEST</span><b>$4m USDC → EURC</b></div><i>→</i><div className="quotes">{mode==="orders"?<><p><span>Issuer order</span><b>$1.0m</b></p><p><span>LP order</span><b>$2.5m</b></p><p><span>Private market</span><b>$0.5m</b></p></>:mode==="inventory"?<><p><span>Issuer inventory</span><b>$2.0m</b></p><p><span>Bank capacity</span><b>$5.0m</b></p><p><span>LP stream</span><b>$3.0m</b></p></>:<><p><span>Issuer</span><b>$2m · 6s</b></p><p><span>Bank</span><b>$5m · 8s</b></p><p><span>LP</span><b>$3m · 4s</b></p></>}</div><i>→</i><div className="selected"><span>ROUTE</span><b>Reserve selected combination</b></div></div></div></section>
}

export function FiatEdgesStory(){
  const [mode,setMode]=useState<"managed"|"p2p"|"issuer">("managed");
  return <section className="fxp-section fx-edges"><div className="fxp-section-head"><div><Label>FIAT AT THE EDGES</Label><h2>The FX market does not need to own every banking rail.</h2><p>Use a managed provider, a direct issuer, or a verified P2P payment route to get into or out of stablecoins. If both sides are already stablecoins, the fiat edges disappear.</p></div></div><div className="fx-edge-tabs"><button type="button" onClick={()=>setMode("managed")} className={mode==="managed"?"active":""}>Managed provider</button><button type="button" onClick={()=>setMode("p2p")} className={mode==="p2p"?"active":""}>Verified P2P</button><button type="button" onClick={()=>setMode("issuer")} className={mode==="issuer"?"active":""}>Direct issuer</button></div><div className="fx-edge-route"><div><span>BRL</span><small>fiat</small></div><i>→</i><div className="edge"><span>{mode==="managed"?"Managed ramp":mode==="p2p"?"Payment verified + escrow release":"Issuer mint / release"}</span><small>{mode==="managed"?"provider confirms incoming payment":mode==="p2p"?"payer pays seller through supported app":"issuer receives local fiat"}</small></div><i>→</i><div><span>USDC</span><small>stablecoin</small></div><i className="accent">→</i><div className="core"><span>FX MARKET</span><small>USDC → EURC</small></div><i className="accent">→</i><div><span>EURC</span><small>stablecoin</small></div><i>→</i><div className="edge"><span>Off-ramp / redeem</span><small>provider-specific</small></div><i>→</i><div><span>EUR</span><small>fiat</small></div></div><div className="fx-edge-note"><div><b>Stablecoin → stablecoin</b><span>USDT → EURC uses the FX market directly. No fiat edge is required.</span></div><div><b>Provider-neutral</b><span>The provider can change without changing the core FX market interface.</span></div></div></section>
}

export function SettlementStates(){
  return <section className="fxp-section fx-states"><div className="fxp-section-head"><div><Label>EXECUTION</Label><h2>Know what has actually settled.</h2><p>A quote is not a fill. Submission is not settlement. Different legs can reach finality in different ways.</p></div></div><div className="fx-state-line"><div><span>PREVIEW</span><small>price only</small></div><i>→</i><div><span>RESERVED</span><small>selected capacity held</small></div><i>→</i><div><span>SUBMITTED</span><small>execution sent</small></div><i>→</i><div className="done"><span>CONFIRMED</span><small>settlement evidence accepted</small></div><div className="failed"><span>FAILED</span><small>release / reconcile</small></div></div><div className="fx-finality"><div><span>TOKEN SWAP</span><b>Atomic when the selected fills execute in one router transaction.</b></div><div><span>FIAT PAYMENT</span><b>Confirmed by external evidence.</b></div><div><span>ISSUER REDEMPTION</span><b>External or asynchronous finality.</b></div></div></section>
}

export function ImplementationExplorer(){
  const [selected,setSelected]=useState(FX_CAPABILITIES[0].id); const capability=FX_CAPABILITIES.find((item)=>item.id===selected)!;
  return <section className="fxp-section fx-impl"><div className="fxp-section-head"><div><Label>DEVELOPERS</Label><h2>It is infrastructure. So here is the infrastructure.</h2><p>Every section below tells you whether the capability is built, reference-only, adapter-ready, or not connected yet — with the source beside it.</p></div></div><div className="fx-impl-layout"><div className="fx-impl-list">{FX_CAPABILITIES.map((item)=><button type="button" key={item.id} className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)}><span className={`status ${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span><b>{item.title}</b></button>)}</div><div className="fx-impl-detail"><div className={`fx-status-big ${capability.status.toLowerCase()}`}>{statusLabel(capability.status)}</div><h3>{capability.title}</h3><p>{capability.summary}</p>{capability.api&&<div className="fx-api-lines">{capability.api.map((line)=><code key={line}>{line}</code>)}</div>}<div className="fx-impl-links"><a href={capabilitySource(capability)} target="_blank" rel="noreferrer">Source ↗</a>{capabilityTest(capability)&&<a href={capabilityTest(capability)!} target="_blank" rel="noreferrer">Tests ↗</a>}</div></div></div></section>
}
