import { useMemo,useState,type ChangeEvent } from "react";
import { CARD_PROGRAMS,type CardProgram,type CardStatus,type CustodyModel } from "./cards/data";
import "./CardsPage.css";
import "./cards/workbench.css";

type CardsPageProps={onNavigate:(path:string)=>void};
type Filter="all"|CustodyModel|"Visa"|"Mastercard"|"Consumer"|"Business"|"legacy";
const FILTERS:{id:Filter;label:string}[]=[{id:"all",label:"All current"},{id:"Self-custodial",label:"Self-custody"},{id:"Custodial",label:"Custodial"},{id:"Hybrid",label:"Hybrid"},{id:"Visa",label:"Visa"},{id:"Mastercard",label:"Mastercard"},{id:"Consumer",label:"Consumer"},{id:"Business",label:"Business"},{id:"legacy",label:"Legacy"}];
const FEATURED=["metamask","plasma","nexo","minipay","kast"];
const PATTERNS=[
 {name:"Wallet-native spending",desc:"Assets stay under user control until the card needs them.",ids:["metamask","solflare","minipay","gnosis-pay"],flow:["WALLET","AUTHORISATION","ISSUER","NETWORK"]},
 {name:"Stablecoin neobank",desc:"Stablecoin balances sit inside an account product with card access layered on top.",ids:["kast","brighty","plasma","coca"],flow:["STABLECOIN","ACCOUNT","CARD PROGRAMME","NETWORK"]},
 {name:"Exchange account",desc:"A custodial trading account becomes the source of funds for everyday card spend.",ids:["okx","krak","bybit","crypto-com"],flow:["ACCOUNT ASSETS","CONVERSION","CARD BALANCE","NETWORK"]},
 {name:"Collateralised spend",desc:"The customer keeps the asset and borrows or receives spending power against it.",ids:["nexo","avalanche","exa","avici"],flow:["COLLATERAL","CREDIT LINE","AUTHORISATION","NETWORK"]},
 {name:"Wallet to regulated account",desc:"Self-custody remains the crypto entry point, then value moves into regulated card infrastructure.",ids:["safepal","ledger-cl","1inch"],flow:["WALLET","CARD ACCOUNT","ISSUER","NETWORK"]}
];
function matchesFilter(c:CardProgram,f:Filter){if(f==="all")return c.status!=="legacy";if(f==="legacy")return c.status==="legacy";if(f==="Visa"||f==="Mastercard")return c.network.includes(f)&&c.status!=="legacy";if(f==="Consumer"||f==="Business")return(c.customer===f||c.customer==="Both")&&c.status!=="legacy";return c.custody===f&&c.status!=="legacy"}
function statusLabel(s:CardStatus){return s==="launching"?"LAUNCHING":s==="legacy"?"LEGACY":"ACTIVE"}
function short(value:string,max=44){return value.length>max?value.slice(0,max-1)+"…":value}

function HeroWorkbench({active,onChange,onCompare}:{active:CardProgram;onChange:(c:CardProgram)=>void;onCompare:(id:string)=>void}){
 const featured=FEATURED.map(id=>CARD_PROGRAMS.find(c=>c.id===id)).filter((c):c is CardProgram=>Boolean(c));
 return <div className="ci-hero-workbench"><div className="ci-workbench-top"><span>LIVE TEARDOWN</span><div>{featured.map(c=><button key={c.id} className={c.id===active.id?"active":""} onClick={()=>onChange(c)}>{c.name.replace(" Card","")}</button>)}</div></div><div className="ci-card-stage"><div className="ci-visual-card"><div className="ci-card-brand"><span>{active.company}</span><b>{active.network}</b></div><strong>{active.name}</strong><small>{active.model}</small><div className="ci-card-dots"><i/><i/></div></div><div className="ci-card-facts"><div><span>CUSTODY</span><b>{active.custody}</b></div><div><span>MARKET OFFER</span><b>{short(active.rewards,62)}</b></div><div><span>FUNDING</span><b>{active.funding.slice(0,4).join(" · ")}</b></div><div><span>MARKETS</span><b>{short(active.geography,58)}</b></div></div></div><div className="ci-flow"><span>{active.wallets}</span><i>→</i><span>{active.spendModel}</span><i>→</i><span>{active.partners[0]||"ISSUER"}</span><i>→</i><span>{active.network}</span></div><div className="ci-workbench-foot"><div><span>KNOWN STACK</span><b>{active.partners.join(" → ")||"Not publicly disclosed"}</b></div><button onClick={()=>onCompare(active.id)}>Add to compare +</button></div></div>
}
function DetailPanel({card,onClose,onCompare,selected}:{card:CardProgram;onClose:()=>void;onCompare:()=>void;selected:boolean}){return <div className="cards-detail-backdrop" onMouseDown={onClose}><aside className="cards-detail" onMouseDown={e=>e.stopPropagation()}><div className="cards-detail-head"><div><span>CARD MODEL</span><h2>{card.name}</h2><p>{card.company} · {card.network} · {card.type}</p></div><button onClick={onClose}>×</button></div><div className="cards-detail-summary"><div><small>CUSTODY</small><b>{card.custody}</b></div><div><small>CUSTOMER</small><b>{card.customer}</b></div><div><small>FORM</small><b>{[card.virtual&&"Virtual",card.physical&&"Physical"].filter(Boolean).join(" + ")||"Not disclosed"}</b></div></div><section><span>HOW IT WORKS</span><h3>{card.model}</h3><p>{card.note}</p><div className="cards-flow"><b>{card.wallets}</b><i>→</i><b>{card.spendModel}</b><i>→</i><b>{card.network}</b><i>→</i><b>Merchant</b></div></section><section><span>MONEY + CUSTOMER OFFER</span><div className="cards-detail-list"><div><small>STABLECOINS / FUNDING</small><b>{card.funding.join(" · ")}</b></div><div><small>CHAINS</small><b>{card.chains.join(" · ")}</b></div><div><small>FEES / FX</small><b>{card.fees}</b></div><div><small>REWARDS / PERKS</small><b>{card.rewards}</b></div></div></section><section><span>KNOWN INFRASTRUCTURE</span><div className="cards-partner-chain">{card.partners.map((p,i)=><span key={p}>{i>0&&<i>→</i>}<b>{p}</b></span>)}</div><p className="cards-disclosure">Unknown issuer, processor, settlement or compliance relationships stay undisclosed rather than being inferred.</p></section><section><span>AVAILABILITY</span><p>{card.geography}</p></section><div className="cards-detail-actions"><button onClick={onCompare}>{selected?"Remove from comparison":"Add to comparison"}</button><button className="secondary" onClick={onClose}>Back</button></div></aside></div>}
const COMPARE_ROWS:Array<[string,(c:CardProgram)=>string]>=[["Product model",c=>c.model],["Card",c=>`${c.network} · ${c.type}`],["Custody",c=>c.custody],["Funding",c=>c.funding.join(" · ")],["Chains",c=>c.chains.join(" · ")],["Spend / authorisation",c=>c.spendModel],["Known stack",c=>c.partners.join(" → ")||"Not publicly disclosed"],["Rewards / perks",c=>c.rewards],["Fees / FX",c=>c.fees],["Markets",c=>c.geography],["Customer",c=>c.customer]];
function CompareWorkspace({cards,onRemove,onClear}:{cards:CardProgram[];onRemove:(id:string)=>void;onClear:()=>void}){const[open,setOpen]=useState(false);if(!cards.length)return null;return <div className="cards-compare-tray"><div className="cards-compare-bar"><div><span>COMPARE PROGRAMS</span><strong>{cards.map(c=>c.name).join(" · ")}</strong></div><div><button className="secondary" onClick={onClear}>Clear</button><button onClick={()=>setOpen(!open)}>{open?"Close":`Compare ${cards.length}`}</button></div></div>{open&&<div className="cards-compare-table-wrap"><table><thead><tr><th>BUILD DECISION</th>{cards.map(c=><th key={c.id}>{c.name}<button onClick={()=>onRemove(c.id)}>×</button></th>)}</tr></thead><tbody>{COMPARE_ROWS.map(([label,get])=><tr key={label}><td>{label}</td>{cards.map(c=><td key={c.id}>{get(c)}</td>)}</tr>)}</tbody></table></div>}</div>}
function MarketTable({cards,selected,onToggle,onOpen}:{cards:CardProgram[];selected:string[];onToggle:(id:string)=>void;onOpen:(c:CardProgram)=>void}){return <div className="ci-table-wrap"><table className="ci-market-table"><thead><tr><th>PROGRAM</th><th>MODEL</th><th>CUSTODY</th><th>FUNDING</th><th>NETWORK</th><th>MARKET OFFER</th><th>FEES / FX</th><th>KNOWN STACK</th><th></th></tr></thead><tbody>{cards.map(c=><tr key={c.id}><td><button className="ci-program" onClick={()=>onOpen(c)}><b>{c.name}</b><span>{statusLabel(c.status)} · {c.company}</span></button></td><td>{c.model}</td><td><span className={`ci-pill ${c.custody==="Self-custodial"?"blue":""}`}>{c.custody}</span></td><td>{c.funding.slice(0,3).join(" · ")}</td><td><b>{c.network}</b></td><td>{short(c.rewards,52)}</td><td>{short(c.fees,48)}</td><td>{c.partners.slice(0,3).join(" → ")||"Not disclosed"}</td><td><button className={`ci-add ${selected.includes(c.id)?"selected":""}`} onClick={()=>onToggle(c.id)}>{selected.includes(c.id)?"✓":"+"}</button></td></tr>)}</tbody></table></div>}
export default function CardsPage({onNavigate}:CardsPageProps){
 const [filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<CardProgram|null>(null),[heroId,setHeroId]=useState("metamask");
 const hero=CARD_PROGRAMS.find(c=>c.id===heroId)||CARD_PROGRAMS[0];
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return CARD_PROGRAMS.filter(c=>matchesFilter(c,filter)).filter(c=>!q||[c.name,c.company,c.network,c.type,c.custody,c.model,c.spendModel,c.rewards,c.fees,c.geography,...c.funding,...c.chains,...c.partners].join(" ").toLowerCase().includes(q))},[filter,query]);
 const compared=selected.map(id=>CARD_PROGRAMS.find(c=>c.id===id)).filter((c):c is CardProgram=>Boolean(c));
 const toggle=(id:string)=>setSelected(cur=>cur.includes(id)?cur.filter(x=>x!==id):cur.length<4?[...cur,id]:cur);
 return <div className="cards-page ci-page"><section className="ci-hero"><div className="ci-hero-copy"><span className="cards-eyebrow">CARD INTELLIGENCE</span><h1>See how the market<br/>is building cards.</h1><p>Study product models, customer economics, stablecoin rails and the infrastructure behind modern card programmes. Built for teams designing neobanks and financial products.</p><div className="cards-hero-actions"><button onClick={()=>document.getElementById("market")?.scrollIntoView({behavior:"smooth"})}>Explore the market</button><button className="secondary" onClick={()=>toggle(hero.id)}>Compare programmes</button></div><div className="ci-proof"><span><b>41</b> public programmes</span><span><b>38</b> current / launching</span><span><b>20+</b> mapped infrastructure relationships</span><span>Updated Aug 2026</span></div></div><HeroWorkbench active={hero} onChange={c=>setHeroId(c.id)} onCompare={toggle}/></section>
 <section id="market" className="ci-section"><div className="ci-section-head"><div><span>MARKET</span><h2>Card programmes</h2><p>What customers are being offered, how funds move and who is publicly known to power the programme.</p></div><label className="cards-search"><span>SEARCH</span><input value={query} onChange={(e:ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)} placeholder="Card, stablecoin, provider, model or region…"/></label></div><div className="cards-filter-row">{FILTERS.map(f=><button className={filter===f.id?"active":""} key={f.id} onClick={()=>setFilter(f.id)}><b>{f.label}</b><span>{CARD_PROGRAMS.filter(c=>matchesFilter(c,f.id)).length}</span></button>)}</div><div className="cards-results-line"><span>{filtered.length} programmes</span><span>Unknown fields remain not publicly disclosed</span></div><MarketTable cards={filtered} selected={selected} onToggle={toggle} onOpen={setDetail}/></section>
 <section className="ci-section"><div className="ci-section-head solo"><div><span>MARKET PATTERNS</span><h2>Five ways the market is putting cards together.</h2><p>These are observable product architectures, not rankings.</p></div></div><div className="ci-pattern-grid">{PATTERNS.map((p,index)=><article className={index===0?"dark":""} key={p.name}><span>0{index+1}</span><h3>{p.name}</h3><p>{p.desc}</p><div className="ci-mini-flow">{p.flow.map((step,i)=><span key={step}>{i>0&&<i>→</i>}<b>{step}</b></span>)}</div><div className="ci-examples">{p.ids.map(id=>{const c=CARD_PROGRAMS.find(x=>x.id===id);return c?<button key={id} onClick={()=>setDetail(c)}>{c.name.replace(" Card","")}</button>:null})}</div></article>)}</div></section>
 <section className="ci-section ci-network"><div className="ci-section-head solo"><div><span>WHO POWERS WHOM</span><h2>The brands are more fragmented than the infrastructure.</h2><p>Follow the publicly confirmed relationships underneath the customer-facing cards.</p></div></div><div className="ci-network-grid"><article className="dark"><span>RAIN</span><strong>Visa issuing + stablecoin infrastructure</strong><p>RedotPay · KAST · ether.fi · Plasma One · Tria · Avalanche · Western Union</p></article><article><span>BAANX</span><strong>Wallet-to-card infrastructure</strong><p>MetaMask · Ledger CL · 1inch</p></article><article><span>GNOSIS PAY</span><strong>Self-custodial card infrastructure</strong><p>MiniPay · Gnosis ecosystem frontends</p></article><article><span>MONAVATE</span><strong>Regulated issuing</strong><p>Gnosis Pay · MiniPay · 1inch</p></article><article className="dark"><span>WIREX</span><strong>Principal member + stablecoin BaaS</strong><p>Wirex One · BingX</p></article><article><span>KULIPA</span><strong>Self-custodial Mastercard infrastructure</strong><p>Solflare · Ready (legacy)</p></article></div></section>
 <section className="cards-bottom ci-bottom"><div><span>FROM MARKET MODEL TO YOUR STACK</span><h2>See a model you want to build?</h2><p>Move into the Providers directory to explore issuing, banking, custody, compliance, FX, stablecoin and payment infrastructure for your own product.</p></div><div><button onClick={()=>onNavigate("/ecosystem")}>Browse providers</button><