export type CardStatus = "active" | "launching" | "legacy";
export type CustodyModel =
  "Custodial" | "Self-custodial" | "Hybrid" | "Not disclosed";

export type CardProgram = {
  id: string;
  name: string;
  company: string;
  network: string;
  type: string;
  custody: CustodyModel;
  funding: string[];
  chains: string[];
  partners: string[];
  geography: string;
  rewards: string;
  fees: string;
  spendModel: string;
  model: string;
  status: CardStatus;
  customer: "Consumer" | "Business" | "Both";
  physical: boolean;
  virtual: boolean;
  wallets: string;
  note: string;
  sourceUrl: string;
  asOf: string;
  jurisdiction: string;
  confidence: "high" | "medium" | "low";
};

type CardProgramBase = Omit<
  CardProgram,
  "sourceUrl" | "asOf" | "jurisdiction" | "confidence"
>;

const CARD_PROGRAMS_BASE: CardProgramBase[] = [
  {
    id: "redotpay",
    name: "RedotPay Card",
    company: "RedotPay",
    network: "Visa",
    type: "Prepaid / debit",
    custody: "Hybrid",
    funding: ["USDT", "USDC"],
    chains: [
      "Arbitrum",
      "Base",
      "BSC",
      "Ethereum",
      "Optimism",
      "Polygon",
      "Solana",
      "TON",
      "TRON",
    ],
    partners: ["Rain", "Visa"],
    geography: "100+ country user footprint claimed",
    rewards: "Credit-spend, Earn and Pro benefits; no universal cashback rate",
    fees: "No annual fee; conversion and international FX apply",
    spendModel: "Custodial balance with newer self-custody USDC option",
    model: "Stablecoin account + card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial account + smart-contract vault",
    note: "Broad chain and ramp coverage; issuer arrangements vary by region.",
  },
  {
    id: "kast",
    name: "KAST Card",
    company: "KAST",
    network: "Visa",
    type: "Prepaid",
    custody: "Custodial",
    funding: ["USDC", "USDT"],
    chains: ["Solana", "Ethereum", "Base", "Arbitrum", "Polygon", "TRON"],
    partners: ["Rain", "Visa"],
    geography: "Broad international positioning",
    rewards: "~2% base / 3% max tracked; premium ecosystem benefits",
    fees: "FX roughly 0.5–1.75% tracked; ATM and tier pricing vary",
    spendModel: "Pre-funded stablecoin neobank balance",
    model: "Stablecoin neobank",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial",
    note: "Rewards, FX and card pricing are tiered rather than one static number.",
  },
  {
    id: "etherfi",
    name: "ether.fi Cash",
    company: "ether.fi",
    network: "Visa",
    type: "Crypto-backed card",
    custody: "Self-custodial",
    funding: ["USDC", "Yield-bearing assets"],
    chains: ["Optimism", "Scroll"],
    partners: ["Rain", "Visa"],
    geography: "Multi-region",
    rewards: "Up to ~3–4%; yield-bearing balances and travel benefits",
    fees: "Current material promotes 0 FX on relevant EUR/USD transactions",
    spendModel: "Direct spend or borrow-to-spend against holdings",
    model: "Self-custody + credit",
    status: "active",
    customer: "Both",
    physical: true,
    virtual: true,
    wallets: "Self-custodial",
    note: "Assets can remain productive while card spending is sourced from them.",
  },
  {
    id: "plasma",
    name: "Plasma One",
    company: "Plasma",
    network: "Visa",
    type: "Consumer card",
    custody: "Self-custodial",
    funding: ["USDT"],
    chains: ["Plasma"],
    partners: ["Rain", "Visa"],
    geography: "Broad acceptance; issuance eligibility narrower",
    rewards:
      "Up to 4% qualifying cashback in XPL; yield around the card balance",
    fees: "No additional Plasma card fee; partner FX/withdrawal fees may apply",
    spendModel: "No manual prepaid top-up; earn until spend",
    model: "Stablecoin-native account",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Self-custodial",
    note: "A clear example of stablecoins as the account substrate rather than a top-up rail.",
  },
  {
    id: "karta",
    name: "Karta",
    company: "Karta",
    network: "Visa",
    type: "Card",
    custody: "Not disclosed",
    funding: ["Not disclosed"],
    chains: ["Base"],
    partners: ["Rain-related settlement", "Visa"],
    geography: "Not sufficiently disclosed",
    rewards: "Not standardized publicly",
    fees: "~0–1% FX tracked",
    spendModel: "Not publicly disclosed",
    model: "Onchain card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Not disclosed",
    note: "Useful precisely because issuer, custody and settlement disclosure is sparse.",
  },
  {
    id: "wirex-one",
    name: "Wirex One",
    company: "Wirex",
    network: "Visa + Mastercard",
    type: "Debit / prepaid",
    custody: "Hybrid",
    funding: ["USDC", "EURC", "Fiat"],
    chains: ["EVM / Wirex infrastructure"],
    partners: ["Visa", "Mastercard", "Wirex"],
    geography: "Wirex says 130+ countries",
    rewards: "0.5% base to as much as 8% promoted by membership",
    fees: "Tracker ~0.35% FX; ATM fees after tier allowance",
    spendModel: "Account balance + stablecoin settlement",
    model: "Consumer card + BaaS",
    status: "active",
    customer: "Both",
    physical: true,
    virtual: true,
    wallets: "Wirex account",
    note: "Wirex is both a consumer competitor and an infrastructure provider.",
  },
  {
    id: "tria",
    name: "Tria Card",
    company: "Tria",
    network: "Visa",
    type: "Card + wallet",
    custody: "Self-custodial",
    funding: ["Stablecoins", "1,000+ funding tokens"],
    chains: ["Arbitrum", "Base", "Optimism", "Polygon", "Solana"],
    partners: ["Rain", "Visa"],
    geography: "Spending advertised in 150+ countries",
    rewards: "~1.5% base to 6% max; stablecoin rewards",
    fees: "~1% FX and ~3% ATM tracked",
    spendModel: "Broad asset funding into self-custodial card flow",
    model: "Multi-asset self-custody",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Threshold-signature wallet",
    note: "Shows that broad front-end asset support does not require every asset to be a settlement asset.",
  },
  {
    id: "gnosis-pay",
    name: "Gnosis Pay",
    company: "Gnosis Pay",
    network: "Visa",
    type: "Debit / white-label",
    custody: "Self-custodial",
    funding: ["EURe", "GBPe"],
    chains: ["Gnosis Chain"],
    partners: ["Monavate", "Safe", "Monerium", "Visa"],
    geography: "Primarily EEA / UK eligible markets",
    rewards: "Frontend-dependent; roughly 1–5% GNO in some programs",
    fees: "Transparent card, ATM and replacement schedule; Visa FX rate",
    spendModel: "Safe smart account to card authorization",
    model: "Self-custodial card infrastructure",
    status: "active",
    customer: "Both",
    physical: true,
    virtual: true,
    wallets: "Safe smart account",
    note: "One of the clearest reusable card infrastructure models in the market.",
  },
  {
    id: "cypher",
    name: "Cypher Card",
    company: "Cypher",
    network: "Visa",
    type: "Prepaid wallet card",
    custody: "Self-custodial",
    funding: ["Multiple stablecoins / crypto"],
    chains: [
      "Arbitrum",
      "Avalanche",
      "Base",
      "Ethereum",
      "Gnosis",
      "Optimism",
      "Polygon",
      "Solana",
    ],
    partners: ["Visa"],
    geography: "Historical multi-region",
    rewards: "Historical variable rewards",
    fees: "Historical terms changed over time",
    spendModel: "Wallet-linked",
    model: "Self-custodial wallet card",
    status: "legacy",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Self-custodial",
    note: "Card spend closed 8 Aug 2026; useful case study in issuer dependency despite self-custody.",
  },
  {
    id: "kolo",
    name: "Kolo Card",
    company: "Kolo",
    network: "Visa",
    type: "Visa Platinum",
    custody: "Hybrid",
    funding: ["USDT", "USDC", "EURC"],
    chains: [
      "Arbitrum",
      "Avalanche",
      "Base",
      "Ethereum",
      "Optimism",
      "Polygon",
    ],
    partners: ["Visa", "Rain-related settlement"],
    geography: "Broad international use",
    rewards: "Intro ~2% BTC cashback then ~1% in current third-party material",
    fees: "~1% FX tracked; newer sources claim 0% on matched stablecoins",
    spendModel: "Architecture disputed / changed",
    model: "MPC wallet + card",
    status: "active",
    customer: "Both",
    physical: false,
    virtual: true,
    wallets: "MPC claims; architecture to verify",
    note: "Keep conflicting custody and FX evidence visible instead of choosing one version.",
  },
  {
    id: "ready",
    name: "Ready Card",
    company: "Ready",
    network: "Mastercard",
    type: "Lite + Metal",
    custody: "Self-custodial",
    funding: ["USDC"],
    chains: ["Starknet"],
    partners: ["Kulipa", "Mastercard"],
    geography: "Historical",
    rewards: "Ready Rewards / historical STRK programs",
    fees: "Metal historically 0% FX; Lite around 1%",
    spendModel: "Self-custodial wallet card",
    model: "Wallet-native Mastercard",
    status: "legacy",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Self-custodial",
    note: "Shut down in 2026; valuable as a failure case for centralized card-program dependency.",
  },
  {
    id: "bfinance",
    name: "BFinance Card",
    company: "BFinance",
    network: "Visa + Mastercard",
    type: "Card",
    custody: "Not disclosed",
    funding: ["Not disclosed"],
    chains: ["Not disclosed"],
    partners: ["Visa", "Mastercard"],
    geography: "Not sufficiently disclosed",
    rewards: "Not disclosed",
    fees: "~1–2% FX tracked",
    spendModel: "Not publicly disclosed",
    model: "Opaque onchain card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Not disclosed",
    note: "One of the least documented tracked programs; blanks are a meaningful data point.",
  },
  {
    id: "metamask",
    name: "MetaMask Card",
    company: "MetaMask",
    network: "Mastercard",
    type: "Debit",
    custody: "Self-custodial",
    funding: ["mUSD", "USDC", "aUSDC", "USDT", "EURe", "GBPe", "wETH"],
    chains: ["Linea", "Solana", "Monad", "Base"],
    partners: ["Baanx", "Mastercard"],
    geography: "Europe, UK, Americas and selected markets",
    rewards: "Programs have included 1–3% and mUSD-linked cashback",
    fees: "~0.5% comparable FX tracked; conversion depends on asset/pair",
    spendModel: "Funds stay in MetaMask until spend",
    model: "Wallet-native JIT spend",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Self-custodial MetaMask wallet",
    note: "US sign-ups and Metal ordering have had temporary pauses; model issuance status separately.",
  },
  {
    id: "holyheld",
    name: "Holyheld Card",
    company: "Holyheld",
    network: "Mastercard",
    type: "Card",
    custody: "Not disclosed",
    funding: ["Stablecoins / crypto"],
    chains: [
      "Arbitrum",
      "Avalanche",
      "Base",
      "BSC",
      "Ethereum",
      "Gnosis",
      "Optimism",
      "Polygon",
      "Solana",
      "zkSync",
    ],
    partners: ["Mastercard"],
    geography: "Multi-region",
    rewards: "0.5% base / 1% max tracked",
    fees: "2.5% FX; separate domestic/international ATM costs",
    spendModel: "Multichain card flow",
    model: "Multichain card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Not sufficiently disclosed",
    note: "Mature multichain footprint with less issuer transparency than many peers.",
  },
  {
    id: "bitget-wallet",
    name: "Bitget Wallet Card",
    company: "Bitget Wallet",
    network: "Visa + Mastercard",
    type: "Regional card programs",
    custody: "Hybrid",
    funding: ["Stablecoins vary by program"],
    chains: ["Arbitrum", "Base", "Ethereum", "Solana", "TRON"],
    partners: ["UR", "Immersve", "DCS", "Visa", "Mastercard"],
    geography: "Multiple markets / issuer-specific",
    rewards: "~2% base tracked; campaign-dependent",
    fees: "~1.7% FX tracked; issuer-dependent",
    spendModel: "Self-custody front end over multiple issuer models",
    model: "Multi-issuer abstraction",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Wallet front end + issuer card accounts",
    note: "Should be modeled as one product with multiple legal card programs underneath.",
  },
  {
    id: "avici",
    name: "Avici Card",
    company: "Avici",
    network: "Visa",
    type: "Top-up / secured credit",
    custody: "Self-custodial",
    funding: ["Crypto / stablecoin collateral"],
    chains: ["Arbitrum", "Avalanche", "Base", "Optimism", "Polygon", "Solana"],
    partners: ["Visa"],
    geography: "Active; credit feature rollout varies",
    rewards: "Collateralized credit is the main proposition",
    fees: "~0.4–1% FX tracked",
    spendModel: "Existing card flow + self-custody secured credit",
    model: "Crypto-secured credit",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Self-custody credit positioning",
    note: "Live and coming-soon features should be versioned separately.",
  },
  {
    id: "safepal",
    name: "SafePal Fiat Gateway",
    company: "SafePal + Fiat24",
    network: "Mastercard",
    type: "Debit",
    custody: "Hybrid",
    funding: ["Crypto converted into fiat account"],
    chains: ["Multichain wallet"],
    partners: ["Fiat24", "Mastercard", "MoonPay"],
    geography: "Broad supported-country list with exclusions",
    rewards: "Swiss IBAN / banking access rather than cashback",
    fees: "No account management fee; fiat rails from ~0.6%",
    spendModel: "Self-custody wallet to regulated fiat/IBAN card",
    model: "Wallet + bank account",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "SafePal self-custody + Fiat24 account",
    note: "SafePal native fiat on-ramp paused in Mar 2026 while third-party ramps remained.",
  },
  {
    id: "solayer",
    name: "Solayer Card",
    company: "Solayer",
    network: "Visa",
    type: "Card",
    custody: "Not disclosed",
    funding: ["Stablecoin funding tracked"],
    chains: ["Solana"],
    partners: ["Visa"],
    geography: "Not sufficiently disclosed",
    rewards: "Not disclosed",
    fees: "~1.5% FX tracked",
    spendModel: "Not publicly disclosed",
    model: "Solana-native card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Not disclosed",
    note: "A useful long-tail program with thin public terms.",
  },
  {
    id: "avalanche",
    name: "Avalanche Card",
    company: "Avalanche / Rain",
    network: "Visa",
    type: "Crypto-backed card",
    custody: "Self-custodial",
    funding: ["USDC", "USDT", "AVAX", "WAVAX"],
    chains: ["Avalanche C-Chain"],
    partners: ["Rain", "Visa"],
    geography: "LATAM/Caribbean origins with U.S. expansion",
    rewards: "Crypto-backed spending; points/promotions may apply",
    fees: "1% FX; $0 monthly / virtual / physical / shipping stated",
    spendModel: "Collateral updates spending power",
    model: "Collateralized card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Self-custody wallet",
    note: "Marketing and legal card type differ by jurisdiction; preserve both.",
  },
  {
    id: "exa",
    name: "Exa Visa Signature",
    company: "Exa / Uphold",
    network: "Visa",
    type: "Crypto-backed credit",
    custody: "Hybrid",
    funding: ["USDC collateral", "BTC", "ETH", "XRP"],
    chains: ["Account abstraction"],
    partners: ["Uphold", "Visa"],
    geography: "Jurisdiction-dependent",
    rewards: "Pay Mode vs borrow/installment proposition",
    fees: "Detailed public pricing not captured",
    spendModel: "Collateral → credit line → purchase → repayment",
    model: "Stablecoin-collateral credit",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Uphold collateral account",
    note: "A fundamentally different model from stablecoin debit cards.",
  },
  {
    id: "tuyo",
    name: "Tuyo Card",
    company: "Tuyo",
    network: "Not disclosed",
    type: "Card",
    custody: "Self-custodial",
    funding: ["USDC"],
    chains: ["Base"],
    partners: ["Regulated partners not named"],
    geography: "International positioning; issuance list not public",
    rewards:
      "Yield continues until spend; reward mechanics on selected purchases",
    fees: "No hidden card / virtual-account fee advertised; FX usually under 1%",
    spendModel: "USDC can remain in an earn strategy until spend",
    model: "Earn-until-spend",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Self-custodial",
    note: "Explicitly separates crypto access from regulated card/KYC access.",
  },
  {
    id: "solflare",
    name: "Solflare Card",
    company: "Solflare",
    network: "Mastercard",
    type: "Debit",
    custody: "Self-custodial",
    funding: ["USDC"],
    chains: ["Solana"],
    partners: ["Kulipa", "Mastercard"],
    geography: "EEA + UK initial availability",
    rewards: "Core perk is direct gasless wallet spend, not headline cashback",
    fees: "~1% non-USD transaction charge in current educational material",
    spendModel: "USDC leaves wallet only at purchase",
    model: "Wallet-native JIT spend",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Self-custodial Solflare",
    note: "One of the cleanest direct-wallet authorization reference models.",
  },
  {
    id: "phantom-cash",
    name: "Phantom Cash Card",
    company: "Phantom",
    network: "Visa",
    type: "Prepaid debit",
    custody: "Hybrid",
    funding: ["CASH", "Bank / crypto inflows"],
    chains: ["Solana"],
    partners: ["Lead Bank", "Visa"],
    geography: "U.S.-oriented",
    rewards: "Yield-like earnings on CASH balance rather than simple cashback",
    fees: "Program-specific cardholder agreement",
    spendModel: "Onchain CASH balance connected to regulated prepaid card",
    model: "Onchain money account",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Phantom + regulated prepaid layer",
    note: "Payroll, bank deposits, transfers, trading and card spend converge on one app balance.",
  },
  {
    id: "hyperbeat",
    name: "Hyperbeat Card",
    company: "Hyperbeat",
    network: "Visa",
    type: "Card",
    custody: "Not disclosed",
    funding: ["Not disclosed"],
    chains: ["HyperEVM"],
    partners: ["Visa"],
    geography: "Early-stage",
    rewards: "No cashback listed",
    fees: "Not disclosed",
    spendModel: "Not publicly disclosed",
    model: "Ecosystem-native card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Not disclosed",
    note: "Keep discoverable without manufacturing values for thinly disclosed fields.",
  },
  {
    id: "bleap",
    name: "Bleap Card",
    company: "Bleap",
    network: "Mastercard",
    type: "Debit",
    custody: "Self-custodial",
    funding: ["USDC"],
    chains: ["Arbitrum", "Solana", "Base"],
    partners: ["Mastercard"],
    geography: "EEA-centered rollout",
    rewards: "USDC cashback; campaigns can reach up to 20%",
    fees: "0% FX advertised; no monthly subscription; ATM allowance",
    spendModel: "Self-custodial stablecoin wallet spend",
    model: "Stablecoin rewards + savings",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Self-custodial / MPC-style",
    note: "Promotional maximum cashback must not be displayed as guaranteed base cashback.",
  },
  {
    id: "coca",
    name: "COCA Visa Card",
    company: "COCA",
    network: "Visa",
    type: "Card",
    custody: "Self-custodial",
    funding: ["USDC", "USDT", "EURC", "EURS"],
    chains: [
      "Ethereum",
      "BNB Chain",
      "Polygon",
      "Avalanche",
      "Arbitrum",
      "Base",
      "Stellar",
    ],
    partners: ["Visa", "Morpho", "Gauntlet"],
    geography: "COCA states ~75 countries",
    rewards: "Up to 8% stablecoin cashback; subscription and travel benefits",
    fees: "Free virtual; matched stablecoin/fiat pairs can receive 0% conversion",
    spendModel: "MPC wallet + card + DeFi yield",
    model: "Self-custody neobank",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "MPC self-custody",
    note: "Detailed product claims are often first-party; keep source provenance with each term.",
  },
  {
    id: "okx",
    name: "OKX Card",
    company: "OKX",
    network: "Mastercard + Visa",
    type: "Regional debit programs",
    custody: "Custodial",
    funding: ["USDC", "USDG", "USDT in selected markets"],
    chains: ["Account-based"],
    partners: ["Mastercard", "Visa"],
    geography: "EEA + selected Asia/Africa programs",
    rewards: "EEA USDG cashback roughly 2–5% depending status/caps",
    fees: "EEA advertises 0 transaction / FX fee with ~0.1% conversion spread",
    spendModel: "Exchange account authorization",
    model: "Regional exchange card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial exchange account",
    note: "Must be modeled as regional card programs, not one global OKX card.",
  },
  {
    id: "krak",
    name: "Krak Card",
    company: "Kraken / Krak",
    network: "Mastercard",
    type: "Debit",
    custody: "Custodial",
    funding: ["Stablecoins", "Fiat", "600+ assets overall"],
    chains: ["Account-based"],
    partners: ["Mastercard", "Kraken"],
    geography: "Selected U.S., UK and Europe",
    rewards: "Up to ~2% cashback; Metal adds premium benefits",
    fees: "Free card; no monthly / annual card fee in current materials",
    spendModel: "Multi-asset spending order from exchange account",
    model: "Multi-currency exchange card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial",
    note: "Stablecoin-supported rather than stablecoin-exclusive.",
  },
  {
    id: "bybit",
    name: "Bybit Card",
    company: "Bybit",
    network: "Mastercard",
    type: "Debit / prepaid",
    custody: "Custodial",
    funding: ["USDT", "USDC", "Other account assets"],
    chains: ["Account-based"],
    partners: ["Mastercard"],
    geography: "30+ country / regional programs",
    rewards: "Cashback / reward points and tier promotions",
    fees: "Highly region-specific",
    spendModel: "Exchange balance conversion",
    model: "Exchange card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial exchange account",
    note: "Fees, limits and benefits need to resolve by card jurisdiction.",
  },
  {
    id: "crypto-com",
    name: "Crypto.com Visa Card",
    company: "Crypto.com",
    network: "Visa",
    type: "Prepaid / debit",
    custody: "Custodial",
    funding: ["USDC", "USDT", "Broad crypto"],
    chains: ["Account-based"],
    partners: ["Visa"],
    geography: "Multiple regional programs worldwide",
    rewards:
      "Top tiers advertise up to ~5% CRO plus lounge/travel/subscription benefits",
    fees: "Tier and region specific; ATM allowances vary",
    spendModel: "Custodial top-up / conversion",
    model: "Tiered exchange card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial app",
    note: "Rewards depend on CRO holding, caps, reimbursements and tier rules.",
  },
  {
    id: "nexo",
    name: "Nexo Card",
    company: "Nexo",
    network: "Mastercard",
    type: "Dual debit / credit",
    custody: "Custodial",
    funding: ["USDC", "USDT", "Broader Nexo assets"],
    chains: ["Account-based"],
    partners: ["Mastercard", "DiPocket"],
    geography: "EEA / eligible European markets",
    rewards: "Up to 2% cashback; yield on eligible unspent assets",
    fees: "No monthly / annual / inactivity fee; loyalty-based ATM allowance",
    spendModel: "Switch between balance spend and collateral-backed credit",
    model: "Dual-mode card",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial",
    note: "A useful comparator for debit versus collateralized credit under one credential.",
  },
  {
    id: "ledger-cl",
    name: "Ledger CL Card",
    company: "Ledger / Baanx",
    network: "Visa",
    type: "Card",
    custody: "Hybrid",
    funding: ["USDT", "USDC", "Crypto"],
    chains: ["Ledger ecosystem → card account"],
    partners: ["Baanx", "Visa", "Ledger"],
    geography: "UK, EEA, Switzerland, U.S. selected states, Brazil, Mexico +",
    rewards: "~1% cashback options in BTC / USDT / USDC in eligible programs",
    fees: "Region-specific Baanx schedule",
    spendModel: "Self-custody until value is moved into Baanx card environment",
    model: "Hardware wallet bridge",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Ledger self-custody → card account",
    note: "Custody changes through the lifecycle; it is not end-to-end hardware self-custody.",
  },
  {
    id: "1inch",
    name: "1inch Card",
    company: "1inch / Baanx",
    network: "Mastercard",
    type: "Prepaid",
    custody: "Hybrid",
    funding: ["USDT", "BTC", "LTC", "XRP", "1INCH"],
    chains: ["Wallet → card account"],
    partners: ["Baanx", "Monavate", "Mastercard"],
    geography: "UK / EEA",
    rewards: "Historical reward programs vary",
    fees: "Secondary comparisons ~1.75% conversion / ~2% ATM; live issuer terms should override",
    spendModel: "Wallet transfer into card infrastructure",
    model: "Wallet-adjacent prepaid",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "1inch wallet + card account",
    note: "Pricing needs strong source freshness because landing-page detail is limited.",
  },
  {
    id: "oobit",
    name: "Oobit Crypto Card",
    company: "Oobit",
    network: "Visa",
    type: "Digital card",
    custody: "Hybrid",
    funding: ["USDT", "BTC", "ETH", "Other crypto"],
    chains: ["External-wallet dependent"],
    partners: ["Visa", "Tether"],
    geography: "Broad/global positioning",
    rewards: "Crypto cashback; promotions up to 10% on eligible transactions",
    fees: "Creating/holding card advertised as free; transaction fee shown before confirmation",
    spendModel: "Connect wallet; convert when paying",
    model: "Wallet-connected spend",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "External wallet connection + Oobit",
    note: "Interoperability with external wallets is more important than exchange-bound funding.",
  },
  {
    id: "brighty",
    name: "Brighty Card",
    company: "Brighty",
    network: "Mastercard",
    type: "Neobank card",
    custody: "Custodial",
    funding: ["USDC", "USDT", "EUR", "GBP", "USD"],
    chains: ["Multiple account / wallet networks"],
    partners: ["Mastercard"],
    geography: "27+ countries claimed",
    rewards: "Savings / vault yield advertised up to ~10% APY",
    fees: "Zero-fee card-spending positioning; exact schedule varies",
    spendModel: "Stablecoin-enabled IBAN / account balance",
    model: "Stablecoin neobank",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial account",
    note: "Yield is a separate account feature and should not be represented as card cashback.",
  },
  {
    id: "xapo",
    name: "Xapo Bank Card",
    company: "Xapo Bank",
    network: "Visa",
    type: "Bank debit",
    custody: "Custodial",
    funding: ["USD", "BTC", "USDC/USDT deposits convert to USD"],
    chains: ["Stablecoin deposit rails"],
    partners: ["Visa", "Xapo Bank"],
    geography: "International eligible-member base",
    rewards: "Up to ~1% BTC cashback plus banking / wealth benefits",
    fees: "0 FX proposition; paid membership",
    spendModel: "Stablecoin deposits convert into bank USD before card spend",
    model: "Stablecoin-funded bank account",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Regulated bank account",
    note: "Stablecoins are primarily a funding rail, not the authorization balance.",
  },
  {
    id: "lemon",
    name: "Lemon Card",
    company: "Lemon",
    network: "Visa",
    type: "Prepaid + separate credit product",
    custody: "Custodial",
    funding: ["USDC", "USDT", "Local fiat", "Crypto"],
    chains: ["Abstracted through Lemon"],
    partners: ["Visa", "Pomelo", "Bridge", "Circle"],
    geography: "Argentina, Peru and LATAM expansion",
    rewards: "Argentina up to ~2% BTC; Peru up to ~1%; promotions vary",
    fees: "Card advertised free; fees differ by country",
    spendModel:
      "Local fiat / stablecoin conversion at payment depending market",
    model: "LATAM crypto-financial account",
    status: "active",
    customer: "Consumer",
    physical: true,
    virtual: true,
    wallets: "Custodial wallet / exchange",
    note: "Local tax and FX treatment can materially change the card model by country.",
  },
  {
    id: "bingx",
    name: "BingX Visa Debit Card",
    company: "BingX",
    network: "Visa",
    type: "Debit",
    custody: "Custodial",
    funding: ["Stablecoin-backed through Wirex"],
    chains: ["Wirex infrastructure"],
    partners: ["Wirex", "Visa"],
    geography: "Wirex says 200+ countries/territories",
    rewards: "Spending / withdrawal / reward features",
    fees: "Detailed BingX schedule not surfaced",
    spendModel: "Exchange brand over turnkey Wirex stack",
    model: "White-label stablecoin card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "BingX / Wirex program",
    note: "A clean example of the customer brand sitting on third-party card BaaS.",
  },
  {
    id: "western-union",
    name: "Western Union Stablecard",
    company: "Western Union / Rain",
    network: "Visa",
    type: "Digital stablecoin card",
    custody: "Custodial",
    funding: ["USDPT"],
    chains: ["Solana"],
    partners: [
      "Western Union",
      "Rain",
      "Visa",
      "Anchorage Digital Bank",
      "Solana",
    ],
    geography: "Announced / rollout-dependent",
    rewards: "Utility-led rather than cashback-led",
    fees: "Not disclosed at announcement stage",
    spendModel: "Remittance / digital-dollar balance to Visa spend",
    model: "Remittance-to-card",
    status: "launching",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Regulated wallet/card architecture",
    note: "Partnership graph is clear; pricing and eligibility are still too new to treat as settled.",
  },
  {
    id: "minipay",
    name: "MiniPay Card",
    company: "Opera / MiniPay",
    network: "Visa",
    type: "Digital debit",
    custody: "Self-custodial",
    funding: ["USDT", "USDC", "cUSD"],
    chains: ["Celo"],
    partners: [
      "Gnosis Pay",
      "Monavate",
      "Visa",
      "Celo",
      "M-Pesa",
      "OPay",
      "Mercado Pago",
    ],
    geography: "46 countries across EEA, Africa, LATAM and Southeast Asia",
    rewards:
      "Selected markets offer stablecoin / XAUt0 cashback; wallet rewards also offered",
    fees: "Selected ramps advertise zero fees; card-specific FX/ATM not fully public",
    spendModel: "Self-custodial wallet extended into card acceptance",
    model: "Emerging-market wallet card",
    status: "active",
    customer: "Consumer",
    physical: false,
    virtual: true,
    wallets: "Self-custodial MiniPay",
    note: "Gnosis Pay is technical enabler/program manager; Monavate supplies regulated issuing.",
  },
  {
    id: "bitpay-legacy",
    name: "BitPay Prepaid Mastercard",
    company: "BitPay",
    network: "Mastercard",
    type: "Prepaid",
    custody: "Hybrid",
    funding: ["USDC", "GUSD", "PAX/USDP", "BUSD historical"],
    chains: ["Wallet → card load"],
    partners: ["Mastercard", "BitPay"],
    geography: "Historical",
    rewards: "No persistent modern cashback proposition",
    fees: "Historical schedule only",
    spendModel: "Self-custody wallet until prepaid load",
    model: "Legacy wallet-load card",
    status: "legacy",
    customer: "Consumer",
    physical: true,
    virtual: false,
    wallets: "Self-custody wallet → prepaid program",
    note: "Historically important ancestor of current stablecoin-load card models.",
  },
];

const CARD_PROVENANCE: Record<
  string,
  Pick<CardProgram, "sourceUrl" | "asOf" | "jurisdiction" | "confidence">
> = {
  redotpay: {
    sourceUrl: "https://www.redotpay.com/card/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies by country",
    confidence: "medium",
  },
  kast: {
    sourceUrl: "https://www.kast.xyz/",
    asOf: "2026-08-20",
    jurisdiction: "Multi-region; eligibility varies",
    confidence: "high",
  },
  etherfi: {
    sourceUrl: "https://www.ether.fi/app/cash",
    asOf: "2026-08-20",
    jurisdiction: "Eligible markets listed by issuer",
    confidence: "high",
  },
  plasma: {
    sourceUrl: "https://www.plasma.to/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "medium",
  },
  karta: {
    sourceUrl: "https://www.karta.io/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies",
    confidence: "low",
  },
  "wirex-one": {
    sourceUrl: "https://wirexapp.com/",
    asOf: "2026-08-20",
    jurisdiction: "EEA and selected markets",
    confidence: "high",
  },
  tria: {
    sourceUrl: "https://www.tria.so/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "medium",
  },
  "gnosis-pay": {
    sourceUrl: "https://gnosispay.com/",
    asOf: "2026-08-20",
    jurisdiction: "EEA and UK eligibility",
    confidence: "high",
  },
  cypher: {
    sourceUrl: "https://www.cypherhq.io/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies",
    confidence: "medium",
  },
  kolo: {
    sourceUrl: "https://kolo.in/",
    asOf: "2026-08-20",
    jurisdiction: "EEA and selected markets",
    confidence: "medium",
  },
  ready: {
    sourceUrl: "https://www.ready.co/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies",
    confidence: "low",
  },
  bfinance: {
    sourceUrl: "https://b.finance/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies",
    confidence: "low",
  },
  metamask: {
    sourceUrl: "https://metamask.io/card/",
    asOf: "2026-08-20",
    jurisdiction: "Eligible countries listed by programme",
    confidence: "high",
  },
  holyheld: {
    sourceUrl: "https://holyheld.com/",
    asOf: "2026-08-20",
    jurisdiction: "EEA eligibility",
    confidence: "high",
  },
  "bitget-wallet": {
    sourceUrl: "https://web3.bitget.com/en/card",
    asOf: "2026-08-20",
    jurisdiction: "Eligible countries listed by programme",
    confidence: "medium",
  },
  avici: {
    sourceUrl: "https://avici.money/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "medium",
  },
  safepal: {
    sourceUrl: "https://www.safepal.com/en/bank",
    asOf: "2026-08-20",
    jurisdiction: "EEA and selected markets",
    confidence: "medium",
  },
  solayer: {
    sourceUrl: "https://solayer.org/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "low",
  },
  avalanche: {
    sourceUrl: "https://www.avalanchecard.com/",
    asOf: "2026-08-20",
    jurisdiction: "Latin America and Caribbean rollout",
    confidence: "high",
  },
  exa: {
    sourceUrl: "https://www.exa.app/",
    asOf: "2026-08-20",
    jurisdiction: "Eligibility varies",
    confidence: "medium",
  },
  tuyo: {
    sourceUrl: "https://tuyo.com/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "low",
  },
  solflare: {
    sourceUrl: "https://www.solflare.com/card/",
    asOf: "2026-08-20",
    jurisdiction: "Eligible markets listed by programme",
    confidence: "medium",
  },
  "phantom-cash": {
    sourceUrl: "https://phantom.com/cash",
    asOf: "2026-08-20",
    jurisdiction: "United States rollout",
    confidence: "high",
  },
  hyperbeat: {
    sourceUrl: "https://hyperbeat.org/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "low",
  },
  bleap: {
    sourceUrl: "https://www.bleap.finance/",
    asOf: "2026-08-20",
    jurisdiction: "EEA eligibility",
    confidence: "medium",
  },
  coca: {
    sourceUrl: "https://coca.xyz/",
    asOf: "2026-08-20",
    jurisdiction: "Eligible countries listed by programme",
    confidence: "medium",
  },
  okx: {
    sourceUrl: "https://www.okx.com/",
    asOf: "2026-08-20",
    jurisdiction: "Selected regions",
    confidence: "medium",
  },
  krak: {
    sourceUrl: "https://www.kraken.com/",
    asOf: "2026-08-20",
    jurisdiction: "UK and EEA eligibility",
    confidence: "medium",
  },
  bybit: {
    sourceUrl: "https://www.bybit.com/en/cards/",
    asOf: "2026-08-20",
    jurisdiction: "Region-specific programmes",
    confidence: "high",
  },
  "crypto-com": {
    sourceUrl: "https://crypto.com/cards",
    asOf: "2026-08-20",
    jurisdiction: "Region-specific programmes",
    confidence: "high",
  },
  nexo: {
    sourceUrl: "https://nexo.com/nexo-card",
    asOf: "2026-08-20",
    jurisdiction: "EEA eligibility",
    confidence: "high",
  },
  "ledger-cl": {
    sourceUrl: "https://www.ledger.com/cl-card",
    asOf: "2026-08-20",
    jurisdiction: "Issuer-defined eligible markets",
    confidence: "high",
  },
  "1inch": {
    sourceUrl: "https://1inch.io/card/",
    asOf: "2026-08-20",
    jurisdiction: "UK and EEA eligibility",
    confidence: "medium",
  },
  oobit: {
    sourceUrl: "https://www.oobit.com/crypto-card",
    asOf: "2026-08-20",
    jurisdiction: "Eligible countries listed by programme",
    confidence: "medium",
  },
  brighty: {
    sourceUrl: "https://brighty.app/",
    asOf: "2026-08-20",
    jurisdiction: "EEA and selected markets",
    confidence: "medium",
  },
  xapo: {
    sourceUrl: "https://www.xapobank.com/",
    asOf: "2026-08-20",
    jurisdiction: "Eligible Xapo Bank members",
    confidence: "medium",
  },
  lemon: {
    sourceUrl: "https://www.lemon.me/",
    asOf: "2026-08-20",
    jurisdiction: "Country-specific Latin American programmes",
    confidence: "medium",
  },
  bingx: {
    sourceUrl: "https://bingx.com/",
    asOf: "2026-08-20",
    jurisdiction: "Rollout dependent",
    confidence: "low",
  },
  "western-union": {
    sourceUrl: "https://corporate.westernunion.com/",
    asOf: "2026-08-20",
    jurisdiction: "Announced; rollout dependent",
    confidence: "medium",
  },
  minipay: {
    sourceUrl: "https://www.minipay.to/card",
    asOf: "2026-08-20",
    jurisdiction: "Eligible countries listed by programme",
    confidence: "high",
  },
  "bitpay-legacy": {
    sourceUrl: "https://www.bitpay.com/card/",
    asOf: "2026-08-20",
    jurisdiction: "Historical United States programme",
    confidence: "high",
  },
};

export const CARD_PROGRAMS: CardProgram[] = CARD_PROGRAMS_BASE.map((card) => {
  const provenance = CARD_PROVENANCE[card.id];
  if (!provenance) throw new Error(`Missing card provenance for ${card.id}`);
  return { ...card, ...provenance };
});

export const CURRENT_PROGRAMS = CARD_PROGRAMS.filter(
  (card) => card.status !== "legacy",
);
export const LEGACY_PROGRAMS = CARD_PROGRAMS.filter(
  (card) => card.status === "legacy",
);
